import type { LidarRelatedToolLink } from '../types/lidar-map-viewer.types';

export const LIDAR_SUPPORTED_EXTENSIONS: ReadonlyArray<string> = ['.las', '.laz'];

export const LIDAR_ACCEPT_ATTR = '.las,.laz,application/octet-stream';

export const LIDAR_FORMATS_LABEL = '.las, .laz';

export const LIDAR_FORMATS_HINT =
  'ASPRS LAS 1.2 point clouds (formats 0–3). LAZ is accepted with a convert-to-LAS warning.';

export const LIDAR_MAX_FILE_BYTES = 80 * 1024 * 1024;

export const LIDAR_DEFAULT_PREVIEW_CAP = 50000;

export const LIDAR_DEFAULT_POINT_SIZE = 2;

export const LIDAR_DEFAULT_OPACITY = 0.85;

/** ASPRS classification labels (common subset). */
export const LIDAR_CLASS_LABELS: Readonly<Record<number, string>> = {
  0: 'Created / Never classified',
  1: 'Unclassified',
  2: 'Ground',
  3: 'Low vegetation',
  4: 'Medium vegetation',
  5: 'High vegetation',
  6: 'Building',
  7: 'Low point (noise)',
  8: 'Model key-point',
  9: 'Water',
  10: 'Rail',
  11: 'Road surface',
  12: 'Overlap',
  13: 'Wire – guard',
  14: 'Wire – conductor',
  15: 'Transmission tower',
  16: 'Wire – connector',
  17: 'Bridge deck',
  18: 'High noise'
};

/** ASPRS-inspired palette for map coloring. */
export const LIDAR_CLASS_COLORS: Readonly<Record<number, string>> = {
  0: '#94a3b8',
  1: '#64748b',
  2: '#a16207',
  3: '#86efac',
  4: '#22c55e',
  5: '#166534',
  6: '#ef4444',
  7: '#f472b6',
  8: '#fbbf24',
  9: '#38bdf8',
  10: '#78716c',
  11: '#57534e',
  12: '#c084fc',
  13: '#facc15',
  14: '#eab308',
  15: '#dc2626',
  16: '#ca8a04',
  17: '#fb923c',
  18: '#e11d48'
};

export const LIDAR_RELATED_TOOLS: ReadonlyArray<LidarRelatedToolLink> = [
  {
    label: 'Point Cloud Viewer',
    description: '3D orbit, Z clip, and intensity coloring',
    path: '/gis-viewers/point-cloud-viewer'
  },
  {
    label: 'DEM Viewer',
    description: 'Elevation colormap and height sampling',
    path: '/gis-viewers/dem-viewer'
  },
  {
    label: 'Contour Map Viewer',
    description: 'Isolines from elevation grids',
    path: '/gis-viewers/contour-map-viewer'
  }
];

/**
 * Tiny 256-point LAS 1.2 sample (SF lon/lat-style offsets) for offline smoke tests.
 * Decoded bytes match /tmp/sample-lidar.las.b64.
 */
export const LIDAR_SAMPLE_BASE64 =
  'TEFTRgAAAAAAAAAAAAAAAAAAAAAAAAAAAQJFYXN5VG9vbEh1YiBTYW1wbGUgICAAAAAAAAAAAAAAAFNhbXBsZSBMQVMgV3JpdGVyICAgIAAAAAAAAAAAAAAAAQDoB+MA4wAAAAAAAAABHAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAB7FK5H4XqEP3sUrkfheoQ/exSuR+F6hD97FK5H4ZpewMP1KFyP4kJAAAAAAAAAAAAK16NwPZpewOxRuB6Fm17ApHA9CtfjQkDiehSuR+FCQClcj8L1aEtA9ihcj8L1PcD//////////+gDAADoAxECAAABAAAAAAAAQI9A//////////9pCQAADQQRAgAAAQAAAAAAAEiPQP//////////WQ4AADIEEQMAAAEAAAAAAABQj0D//////////zoSAABXBBEEAAABAAAAAAAAWI9A//////////+oFAAAfAQRBQAAAQAAAAAAAGCPQAAAAAD/////ahUAAKEEEQYAAAEAAAAAAABoj0AAAAAA/////3UUAADGBBEJAAABAAAAAAAAcI9AAAAAAP////80DwAA6wQRAgAAAQAAAAAAAHiPQAAAAAD/////cQsAABAFEQIAAAEAAAAAAACAj0AAAAAA/////+QGAAA1BREDAAABAAAAAAAAiI9AAAAAAP////8aAgAAWgURBAAAAQAAAAAAAJCPQAAAAAD/////o/3//38FEQUAAAEAAAAAAACYj0AAAAAA/////wn6//+kBREGAAABAAAAAAAAoI9AAQAAAP////+89///yQURCQAAAQAAAAAAAKiPQAEAAAD/////TPT//+4FEQIAAAEAAAAAAACwj0ABAAAA/////1D1//8TBhECAAABAAAAAAAAuI9A//////////+wBAAAOAYRAwAAAQAAAAAAAMCPQP//////////CAoAAF0GEQQAAAEAAAAAAADIj0D//////////9UOAACCBhEFAAABAAAAAAAA0I9A//////////+ZEgAApwYRBgAAAQAAAAAAANiPQP//////////9xQAAMwGEQkAAAEAAAAAAADgj0AAAAAA//////oSAADxBhECAAABAAAAAAAA6I9AAAAAAP////8QEgAAFgcRAgAAAQAAAAAAAPCPQAAAAAD/////og8AADsHEQMAAAEAAAAAAAD4j0AAAAAA/////wAMAABgBxEEAAABAAAAAAAAAJBAAAAAAP////+bBwAAhQcRBQAAAQAAAAAAAASQQAAAAAD/////+QIAAKoHEQYAAAEAAAAAAAAIkEAAAAAA/////6n+///PBxEJAAABAAAAAAAADJBAAAAAAP////9z+P//9AcRAgAAAQAAAAAAABCQQAEAAAD/////O/b//xkIEQIAAAEAAAAAAAAUkEABAAAA/////5D1//8+CBEDAAABAAAAAAAAGJBAAQAAAP////+Q9v//YwgRBAAAAQAAAAAAAByQQP//////////eAUAAIgIEQUAAAEAAAAAAAAgkED//////////1kKAACtCBEGAAABAAAAAAAAJJBA//////////+7DgAA0ggRCQAAAQAAAAAAACiQQP//////////cg8AAPcIEQIAAAEAAAAAAAAskED//////////6ARAAAcCRECAAABAAAAAAAAMJBAAAAAAP////9WEgAAQQkRAwAAAQAAAAAAADSQQAAAAAD/////jBEAAGYJEQQAAAEAAAAAAAA4kEAAAAAA/////2IPAACLCREFAAABAAAAAAAAPJBAAAAAAP////8hDAAAsAkRBgAAAQAAAAAAAECQQAAAAAD/////LwgAANUJEQkAAAEAAAAAAABEkEAAAAAA/////0sBAAD6CRECAAABAAAAAAAASJBAAAAAAP////9s/f//HwoRAgAAAQAAAAAAAEyQQAAAAAD/////T/r//0QKEQMAAAEAAAAAAABQkEABAAAA/////1f4//9pChEEAAABAAAAAAAAVJBAAQAAAP/////F9///jgoRBQAAAQAAAAAAAFiQQAEAAAD/////tvj//7MKEQYAAAEAAAAAAABckED//////////0AGAADYChEJAAABAAAAAAAAYJBA//////////+mBwAA/QoRAgAAAQAAAAAAAGSQQP//////////XgsAACILEQIAAAEAAAAAAABokED//////////08OAABHCxEDAAABAAAAAAAAbJBA//////////8xEAAAbAsRBAAAAQAAAAAAAHCQQAAAAAD/////2RAAAJELEQUAAAEAAAAAAAB0kEAAAAAA/////0EQAAC2CxEGAAABAAAAAAAAeJBAAAAAAP////+EDgAA2wsRCQAAAQAAAAAAAHyQQAAAAAD/////IgkAAAAMEQIAAAEAAAAAAACAkEAAAAAA/////+kFAAAlDBECAAABAAAAAAAAhJBAAAAAAP////+CAgAASgwRAwAAAQAAAAAAAIiQQAAAAAD/////Wf///28MEQQAAAEAAAAAAACMkEAAAAAA/////9H8//+UDBEFAAABAAAAAAAAkJBAAQAAAP////89+///uQwRBgAAAQAAAAAAAJSQQAEAAAD/////1Pr//94MEQkAAAEAAAAAAACYkEABAAAA//////H4//8DDRECAAABAAAAAAAAnJBA//////////9MBAAAKA0RAgAAAQAAAAAAAKCQQP//////////cwcAAE0NEQMAAAEAAAAAAACkkED//////////0wKAAByDREEAAABAAAAAAAAqJBA//////////+TDAAAlw0RBQAAAQAAAAAAAKyQQP//////////EQ4AALwNEQYAAAEAAAAAAACwkEAAAAAA/////6cOAADhDREJAAABAAAAAAAAtJBAAAAAAP////+VCwAABg4RAgAAAQAAAAAAALiQQAAAAAD/////ZwoAACsOEQIAAAEAAAAAAAC8kEAAAAAA/////4wIAABQDhEDAAABAAAAAAAAwJBAAAAAAP////9FBgAAdQ4RBAAAAQAAAAAAAMSQQAAAAAD/////3AMAAJoOEQUAAAEAAAAAAADIkEAAAAAA/////6EBAAC/DhEGAAABAAAAAAAAzJBAAAAAAP/////c////5A4RCQAAAQAAAAAAANCQQAEAAAD/////EPz//wkPEQIAAAEAAAAAAADUkEABAAAA/////937//8uDxECAAABAAAAAAAA2JBAAQAAAP////+Y/P//Uw8RAwAAAQAAAAAAANyQQP////8AAAAAFAUAAHgPEQQAAAEAAAAAAADgkED/////AAAAABUHAACdDxEFAAABAAAAAAAA5JBA/////wAAAADoCAAAwg8RBgAAAQAAAAAAAOiQQP////8AAAAAZQoAAOcPEQkAAAEAAAAAAADskED/////AAAAALIIAAAMEBECAAABAAAAAAAA8JBAAAAAAAAAAAAzCQAAMRARAgAAAQAAAAAAAPSQQAAAAAAAAAAAKwkAAFYQEQMAAAEAAAAAAAD4kEAAAAAAAAAAAKQIAAB7EBEEAAABAAAAAAAA/JBAAAAAAAAAAAC5BwAAoBARBQAAAQAAAAAAAACRQAAAAAAAAAAAjgYAAMUQEQYAAAEAAAAAAAAEkUAAAAAAAAAAAFAFAADqEBEJAAABAAAAAAAACJFAAAAAAAAAAABwAQAADxERAgAAAQAAAAAAAAyRQAAAAAAAAAAAkQAAADQREQIAAAEAAAAAAAAQkUABAAAAAAAAABwAAABZEREDAAABAAAAAAAAFJFAAQAAAAAAAAAoAAAAfhERBAAAAQAAAAAAABiRQAEAAAAAAAAAvwAAAKMREQUAAAEAAAAAAAAckUD/////AAAAANwFAADIEREGAAABAAAAAAAAIJFA/////wAAAACdBgAA7RERCQAAAQAAAAAAACSRQP////8AAAAAlwQAABISEQIAAAEAAAAAAAAokUD/////AAAAADoFAAA3EhECAAABAAAAAAAALJFA/////wAAAADDBQAAXBIRAwAAAQAAAAAAADCRQAAAAAAAAAAALgYAAIESEQQAAAEAAAAAAAA0kUAAAAAAAAAAAHkGAACmEhEFAAABAAAAAAAAOJFAAAAAAAAAAACpBgAAyxIRBgAAAQAAAAAAADyRQAAAAAAAAAAAwQYAAPASEQkAAAEAAAAAAABAkUAAAAAAAAAAABAEAAAVExECAAABAAAAAAAARJFAAAAAAAAAAAAWBAAAOhMRAgAAAQAAAAAAAEiRQAAAAAAAAAAAIgQAAF8TEQMAAAEAAAAAAABMkUAAAAAAAAAAAD4EAACEExEEAAABAAAAAAAAUJFAAQAAAAAAAABxBAAAqRMRBQAAAQAAAAAAAFSRQAEAAAAAAAAAwQQAAM4TEQYAAAEAAAAAAABYkUABAAAAAAAAADEFAADzExEJAAABAAAAAAAAXJFA/////wAAAADoAwAAGBQRAgAAAQAAAAAAAGCRQP////8AAAAAYwMAAD0UEQIAAAEAAAAAAABkkUD/////AAAAAPcCAABiFBEDAAABAAAAAAAAaJFA/////wAAAAC8AgAAhxQRBAAAAQAAAAAAAGyRQP////8AAAAAwwIAAKwUEQUAAAEAAAAAAABwkUAAAAAAAAAAABYDAADRFBEGAAABAAAAAAAAdJFAAAAAAAAAAAC4AwAA9hQRCQAAAQAAAAAAAHiRQAAAAAAAAAAA5AEAABsVEQIAAAEAAAAAAAB8kUAAAAAAAAAAAAYDAABAFRECAAABAAAAAAAAgJFAAAAAAAAAAABLBAAAZRURAwAAAQAAAAAAAISRQAAAAAAAAAAAnAUAAIoVEQQAAAEAAAAAAACIkUAAAAAAAAAAAN0GAACvFREFAAABAAAAAAAAjJFAAAAAAAAAAAD4BwAA1BURBgAAAQAAAAAAAJCRQAEAAAAAAAAA1ggAAPkVEQkAAAEAAAAAAACUkUABAAAAAAAAALAGAAAeFhECAAABAAAAAAAAmJFAAQAAAAAAAAD4BgAAQxYRAgAAAQAAAAAAAJyRQP////8AAAAAsAQAAGgWEQMAAAEAAAAAAACgkUD/////AAAAAPMCAACNFhEEAAABAAAAAAAApJFA/////wAAAABzAQAAshYRBQAAAQAAAAAAAKiRQP////8AAAAAYwAAANcWEQYAAAEAAAAAAACskUD/////AAAAAO7////8FhEJAAABAAAAAAAAsJFAAAAAAAAAAABv/f//IRcRAgAAAQAAAAAAALSRQAAAAAAAAAAAYv7//0YXEQIAAAEAAAAAAAC4kUAAAAAAAAAAAPz///9rFxEDAAABAAAAAAAAvJFAAAAAAAAAAAAbAgAAkBcRBAAAAQAAAAAAAMCRQAAAAAAAAAAAjQQAALUXEQUAAAEAAAAAAADEkUAAAAAAAAAAABkHAADaFxEGAAABAAAAAAAAyJFAAAAAAAAAAACCCQAA/xcRCQAAAQAAAAAAAMyRQAAAAAAAAAAA1AgAACQYEQIAAAEAAAAAAADQkUABAAAAAAAAAFYKAABJGBECAAABAAAAAAAA1JFAAQAAAAAAAAAvCwAAbhgRAwAAAQAAAAAAANiRQAEAAAAAAAAAUAsAAJMYEQQAAAEAAAAAAADckUD/////AAAAAHgFAAC4GBEFAAABAAAAAAAA4JFA/////wAAAACmAgAA3RgRBgAAAQAAAAAAAOSRQP////8AAAAALgAAAAIZEQkAAAEAAAAAAADokUD/////AAAAAKb7//8nGRECAAABAAAAAAAA7JFA/////wAAAADC+v//TBkRAgAAAQAAAAAAAPCRQAAAAAAAAAAA6/r//3EZEQMAAAEAAAAAAAD0kUAAAAAAAAAAACf8//+WGREEAAABAAAAAAAA+JFAAAAAAAAAAABf/v//uxkRBQAAAQAAAAAAAPyRQAAAAAAAAAAAXwEAAOAZEQYAAAEAAAAAAAAAkkAAAAAAAAAAAN0EAAAFGhEJAAABAAAAAAAABJJAAAAAAAAAAADHBQAAKhoRAgAAAQAAAAAAAAiSQAAAAAAAAAAAOAkAAE8aEQIAAAEAAAAAAAAMkkAAAAAAAAAAAB4MAAB0GhEDAAABAAAAAAAAEJJAAQAAAAAAAAAyDgAAmRoRBAAAAQAAAAAAABSSQAEAAAAAAAAARg8AAL4aEQUAAAEAAAAAAAAYkkABAAAAAAAAAEUPAADjGhEGAAABAAAAAAAAHJJA/////wAAAABABgAACBsRCQAAAQAAAAAAACCSQP////8AAAAAz////y0bEQIAAAEAAAAAAAAkkkD/////AAAAAI78//9SGxECAAABAAAAAAAAKJJA/////wAAAAAn+v//dxsRAwAAAQAAAAAAACySQP////8AAAAA6fj//5wbEQQAAAEAAAAAAAAwkkAAAAAAAAAAAAL5///BGxEFAAABAAAAAAAANJJAAAAAAAAAAAB6+v//5hsRBgAAAQAAAAAAADiSQAAAAAAAAAAAM/3//wscEQkAAAEAAAAAAAA8kkAAAAAAAAAAAC/+//8wHBECAAABAAAAAAAAQJJAAAAAAAAAAACIAgAAVRwRAgAAAQAAAAAAAESSQAAAAAAAAAAAEwcAAHocEQMAAAEAAAAAAABIkkAAAAAAAAAAAFoLAACfHBEEAAABAAAAAAAATJJAAAAAAAAAAADxDgAAxBwRBQAAAQAAAAAAAFCSQAEAAAAAAAAAfREAAOkcEQYAAAEAAAAAAABUkkABAAAAAAAAAMESAAAOHREJAAABAAAAAAAAWJJAAQAAAAAAAADpDwAAMx0RAgAAAQAAAAAAAFySQP////8AAAAATAQAAFgdEQIAAAEAAAAAAABgkkD/////AAAAAPb///99HREDAAABAAAAAAAAZJJA/////wAAAAAm/P//oh0RBAAAAQAAAAAAAGiSQP////8AAAAAUfn//8cdEQUAAAEAAAAAAABskkD/////AAAAANP3///sHREGAAABAAAAAAAAcJJAAAAAAAAAAADg9///ER4RCQAAAQAAAAAAAHSSQAAAAAAAAAAAxvb//zYeEQIAAAEAAAAAAAB4kkAAAAAAAAAAANv5//9bHhECAAABAAAAAAAAfJJAAAAAAAAAAAAV/v//gB4RAwAAAQAAAAAAAICSQAAAAAAAAAAACgMAAKUeEQQAAAEAAAAAAACEkkAAAAAAAAAAADkIAADKHhEFAAABAAAAAAAAiJJAAAAAAAAAAAAZDQAA7x4RBgAAAQAAAAAAAIySQAAAAAAAAAAALhEAABQfEQkAAAEAAAAAAACQkkABAAAAAAAAAFMRAAA5HxECAAABAAAAAAAAlJJAAQAAAAAAAAC5EgAAXh8RAgAAAQAAAAAAAJiSQAEAAAAAAAAAiRIAAIMfEQMAAAEAAAAAAACckkD/////AAAAABQFAACoHxEEAAABAAAAAAAAoJJA/////wAAAABoAAAAzR8RBQAAAQAAAAAAAKSSQP////8AAAAAS/z///IfEQYAAAEAAAAAAACokkD/////AAAAADz5//8XIBEJAAABAAAAAAAArJJA/////wAAAADf9P//PCARAgAAAQAAAAAAALCSQAAAAAAAAAAA5vT//2EgEQIAAAEAAAAAAAC0kkAAAAAAAAAAAJ/2//+GIBEDAAABAAAAAAAAuJJAAAAAAAAAAADl+f//qyARBAAAAQAAAAAAALySQAAAAAAAAAAAZf7//9AgEQUAAAEAAAAAAADAkkAAAAAAAAAAAK0DAAD1IBEGAAABAAAAAAAAxJJAAAAAAAAAAAAzCQAAGiERCQAAAQAAAAAAAMiSQAAAAAAAAAAAqQsAAD8hEQIAAAEAAAAAAADMkkAAAAAAAAAAAAEQAABkIRECAAABAAAAAAAA0JJAAQAAAAAAAAAPEwAAiSERAwAAAQAAAAAAANSSQAEAAAAAAAAAiBQAAK4hEQQAAAEAAAAAAADYkkABAAAAAAAAAE0UAADTIREFAAABAAAAAAAA3JJA/////wEAAADcBQAA+CERBgAAAQAAAAAAAOCSQP////8BAAAAKwEAAB0iEQkAAAEAAAAAAADkkkD/////AQAAAE36//9CIhECAAABAAAAAAAA6JJA/////wEAAAA69///ZyIRAgAAAQAAAAAAAOySQP////8BAAAAl/X//4wiEQMAAAEAAAAAAADwkkAAAAAAAQAAAJ71//+xIhEEAAABAAAAAAAA9JJAAAAAAAEAAABY9///1iIRBQAAAQAAAAAAAPiSQAAAAAABAAAAofr///siEQYAAAEAAAAAAAD8kkAAAAAAAQAAACb///8gIxEJAAABAAAAAAAAAJNAAAAAAAEAAAC3AQAARSMRAgAAAQAAAAAAAASTQAAAAAABAAAAQgcAAGojEQIAAAEAAAAAAAAIk0AAAAAAAQAAAHkMAACPIxEDAAABAAAAAAAADJNAAAAAAAEAAADVEAAAtCMRBAAAAQAAAAAAABCTQAEAAAABAAAA5hMAANkjEQUAAAEAAAAAAAAUk0ABAAAAAQAAAGAVAAD+IxEGAAABAAAAAAAAGJNAAQAAAAEAAAAlFQAAIyQRCQAAAQAAAAAAAByTQP////8BAAAA6AMAAEgkEQIAAAEAAAAAAAAgk0D/////AQAAAIL///9tJBECAAABAAAAAAAAJJNA/////wEAAACk+///kiQRAwAAAQAAAAAAACiTQP////8BAAAAxPj//7ckEQQAAAEAAAAAAAAsk0D/////AQAAAD/3///cJBEFAAABAAAAAAAAMJNAAAAAAAEAAABL9///ASURBgAAAQAAAAAAADSTQAAAAAABAAAA8vj//yYlEQkAAAEAAAAAAAA4k0AAAAAAAQAAAFP5//9LJRECAAABAAAAAAAAPJNAAAAAAAEAAACb/f//cCURAgAAAQAAAAAAAECTQAAAAAABAAAAnwIAAJUlEQMAAAEAAAAAAABEk0AAAAAAAQAAAN4HAAC6JREEAAABAAAAAAAASJNAAAAAAAEAAADODAAA3yURBQAAAQAAAAAAAEyTQAAAAAABAAAA7xAAAAQmEQYAAAEAAAAAAABQk0ABAAAAAQAAANgTAAApJhEJAAABAAAAAAAAVJNAAQAAAAEAAACGEgAATiYRAgAAAQAAAAAAAFiTQAEAAAABAAAAVBIAAHMmEQIAAAEAAAAAAABck0D/////AQAAALAEAACYJhEDAAABAAAAAAAAYJNA/////wEAAADiAAAAvSYRBAAAAQAAAAAAAGSTQP////8BAAAAiv3//+ImEQUAAAEAAAAAAABok0D/////AQAAABL7//8HJxEGAAABAAAAAAAAbJNA/////wEAAADK+f//LCcRCQAAAQAAAAAAAHCTQAAAAAABAAAAJff//1EnEQIAAAEAAAAAAAB0k0AAAAAAAQAAAKP4//92JxECAAABAAAAAAAAeJNAAAAAAAEAAABr+///mycRAwAAAQAAAAAAAHyTQAAAAAABAAAAN////8AnEQQAAAEAAAAAAACAk0AAAAAAAQAAAKkDAADlJxEFAAABAAAAAAAAhJNAAAAAAAEAAABNCAAACigRBgAAAQAAAAAAAIiTQAAAAAABAAAArQwAAC8oEQkAAAEAAAAAAACMk0AAAAAAAQAAAJwNAABUKBECAAABAAAAAAAAkJNAAQAAAAEAAAA1EAAAeSgRAgAAAQAAAAAAAJSTQAEAAAABAAAAfxEAAJ4oEQMAAAEAAAAAAACYk0ABAAAAAQAAAF8RAADDKBEEAAABAAAAAAAAnJNA';
