import { ToolMetadataOverride } from './types';

/**
 * Curated enrichment for high-traffic tools.
 * Keyed by normalized path (leading slash).
 * Auto-derivation still applies for all other tools.
 */
export const TOOL_METADATA_OVERRIDES: Record<string, ToolMetadataOverride> = {
  '/image-color-tools/image-compressor': {
    actions: ['compress', 'optimize', 'resize'],
    objects: ['image', 'photo', 'picture', 'jpg', 'jpeg', 'png', 'webp'],
    inputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    outputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    keywords: [
      'image compressor',
      'photo compressor',
      'reduce image size',
      'shrink image',
      'compress photo',
    ],
    synonyms: [
      'make image smaller',
      'make photo smaller',
      'reduce photo size',
      'lower image file size',
      'shrink photo',
      'optimise image',
      'optimize images for upload',
    ],
    useCases: [
      'reduce image file size',
      'prepare images for websites',
      'send smaller images by email',
      'optimize images for upload',
      'photo too large to email',
    ],
    tags: ['image', 'compression', 'optimization', 'file-size'],
    qualityScore: 0.95,
  },
  '/image-color-tools/image-resizer': {
    actions: ['resize', 'crop', 'scale'],
    objects: ['image', 'photo', 'picture'],
    inputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    outputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    keywords: ['image resizer', 'resize photo', 'change image dimensions'],
    synonyms: ['make picture bigger', 'scale image', 'change photo size', 'crop image'],
    useCases: ['resize photos for social media', 'scale assets for web'],
    tags: ['image', 'resize', 'crop'],
    qualityScore: 0.9,
  },
  '/image-color-tools/image-to-base64': {
    actions: ['convert', 'encode'],
    objects: ['image'],
    inputFormats: ['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg'],
    outputFormats: ['base64'],
    keywords: ['image to base64', 'encode image'],
    synonyms: ['convert image to base64', 'embed image as base64'],
    useCases: ['embed images in CSS or HTML'],
    tags: ['image', 'base64', 'convert'],
    qualityScore: 0.75,
  },
  '/image-color-tools/image-to-text': {
    actions: ['extract', 'convert'],
    objects: ['image', 'text'],
    keywords: ['ocr', 'image to text', 'extract text from image'],
    synonyms: ['read text from photo', 'scan image text'],
    useCases: ['copy text from a screenshot or photo'],
    tags: ['image', 'ocr', 'text'],
    qualityScore: 0.85,
  },
  '/pdf-tools/compress-pdf': {
    actions: ['compress', 'optimize'],
    objects: ['pdf', 'document'],
    inputFormats: ['pdf'],
    outputFormats: ['pdf'],
    keywords: ['compress pdf', 'reduce pdf size', 'pdf compressor'],
    synonyms: [
      'make pdf smaller',
      'shrink pdf',
      'pdf too large',
      'reduce pdf file size',
      'lighten document',
    ],
    useCases: [
      'reduce pdf file size',
      'email a smaller pdf',
      'upload pdf under size limit',
    ],
    tags: ['pdf', 'compression', 'file-size'],
    qualityScore: 0.95,
  },
  '/pdf-tools/merge-pdfs': {
    actions: ['merge'],
    objects: ['pdf', 'document'],
    inputFormats: ['pdf'],
    outputFormats: ['pdf'],
    keywords: ['merge pdfs', 'combine pdf', 'join pdf files'],
    synonyms: [
      'combine multiple pdf files',
      'join pdfs',
      'put pdfs together',
      'concatenate pdf',
    ],
    useCases: ['combine scanned documents', 'merge reports into one pdf'],
    tags: ['pdf', 'merge'],
    qualityScore: 0.95,
  },
  '/pdf-tools/split-pdfs': {
    actions: ['split'],
    objects: ['pdf', 'document'],
    inputFormats: ['pdf'],
    outputFormats: ['pdf'],
    keywords: ['split pdf', 'separate pdf pages'],
    synonyms: ['split pdf pages', 'break pdf into pages'],
    useCases: ['split a large pdf into smaller files'],
    tags: ['pdf', 'split'],
    qualityScore: 0.9,
  },
  '/pdf-tools/extract-pages': {
    actions: ['split', 'extract'],
    objects: ['pdf', 'document'],
    inputFormats: ['pdf'],
    outputFormats: ['pdf'],
    keywords: ['extract pdf pages', 'pull pages from pdf'],
    synonyms: ['extract pages from pdf', 'save selected pdf pages'],
    useCases: ['keep only certain pages from a pdf'],
    tags: ['pdf', 'extract'],
    qualityScore: 0.88,
  },
  '/fun-tools/qr-code-generator': {
    actions: ['generate'],
    objects: ['qr'],
    keywords: ['qr code generator', 'create qr code', 'make qr'],
    synonyms: [
      'make a qr code for my website',
      'create qr code',
      'generate qr for link',
      'make qr for website',
    ],
    useCases: ['create a scannable qr code for a url or text'],
    tags: ['qr', 'generator'],
    qualityScore: 0.95,
  },
  '/data-converters/json-formatter-beautifier-validator': {
    actions: ['format', 'validate'],
    objects: ['json'],
    inputFormats: ['json'],
    outputFormats: ['json'],
    keywords: ['json formatter', 'pretty json', 'validate json'],
    synonyms: [
      'format json',
      'make json readable',
      'beautify json',
      'prettify json',
      'pretty print json',
    ],
    useCases: ['format messy json', 'validate json syntax'],
    tags: ['json', 'format', 'validate'],
    qualityScore: 0.95,
  },
  '/text-utilities/character-counter': {
    actions: ['count'],
    objects: ['text'],
    keywords: ['word counter', 'character counter', 'count words'],
    synonyms: [
      'how many words are in this text',
      'count words',
      'word count',
      'character count',
    ],
    useCases: ['count words and characters in text'],
    tags: ['text', 'count'],
    qualityScore: 0.92,
  },
  '/text-utilities/text-case-convertor': {
    actions: ['convert', 'format'],
    objects: ['text'],
    keywords: ['case converter', 'uppercase', 'lowercase', 'title case'],
    synonyms: ['change text case', 'convert to uppercase', 'make lowercase'],
    useCases: ['switch between upper, lower, and title case'],
    tags: ['text', 'case'],
    qualityScore: 0.88,
  },
};

/** Category → default objects for auto-derivation. */
export const CATEGORY_OBJECT_HINTS: Record<string, string[]> = {
  'pdf-tools': ['pdf', 'document'],
  'image-color-tools': ['image', 'color'],
  'data-converters': ['json', 'csv', 'yaml', 'data'],
  'text-utilities': ['text'],
  'media-audio-tools': ['audio', 'video', 'media'],
  'fun-tools': [],
  'file-code-tools': ['file', 'code'],
};
