import type { ComingSoonToolConfig } from '../types/coming-soon-tool.types';

export const DEFAULT_COMING_SOON_TOOL: ComingSoonToolConfig = {
  slug: 'coming-soon',
  title: 'Coming Soon Viewer',
  tagline: 'A specialized file viewer is on the way.',
  formatsLabel: 'Multiple formats planned',
  roadmap: ['Local parsing', 'Interactive preview', 'Export helpers'],
  liveMessage: 'Soon this tool will be live',
};

export const COMING_SOON_TOOLS: Record<string, ComingSoonToolConfig> = {
  'subtitle-viewer': {
    slug: 'subtitle-viewer',
    title: 'Subtitle Viewer',
    tagline: 'Subtitle timeline review.',
    formatsLabel: '.srt, .vtt',
    roadmap: ['Cues', 'Search'],
    liveMessage: 'Soon this tool will be live',
  },
  'midi-viewer': {
    slug: 'midi-viewer',
    title: 'MIDI Viewer',
    tagline: 'MIDI event / piano-roll view.',
    formatsLabel: '.mid, .midi',
    roadmap: ['Tracks', 'Notes'],
    liveMessage: 'Soon this tool will be live',
  },
  'musicxml-viewer': {
    slug: 'musicxml-viewer',
    title: 'MusicXML Viewer',
    tagline: 'Sheet music markup preview.',
    formatsLabel: '.musicxml, .mxl',
    roadmap: ['Staves', 'Playback cues'],
    liveMessage: 'Soon this tool will be live',
  },
  'apk-viewer': {
    slug: 'apk-viewer',
    title: 'APK Viewer',
    tagline: 'Android package metadata.',
    formatsLabel: '.apk',
    roadmap: ['Manifest', 'Permissions'],
    liveMessage: 'Soon this tool will be live',
  },
  'ipa-viewer': {
    slug: 'ipa-viewer',
    title: 'IPA Viewer',
    tagline: 'iOS package metadata.',
    formatsLabel: '.ipa',
    roadmap: ['Info.plist', 'Entitlements'],
    liveMessage: 'Soon this tool will be live',
  },
  'elf-binary-viewer': {
    slug: 'elf-binary-viewer',
    title: 'ELF Binary Viewer',
    tagline: 'ELF headers and sections.',
    formatsLabel: 'ELF binaries',
    roadmap: ['Headers', 'Sections'],
    liveMessage: 'Soon this tool will be live',
  },
  'pe-binary-viewer': {
    slug: 'pe-binary-viewer',
    title: 'PE Binary Viewer',
    tagline: 'Windows PE inspection.',
    formatsLabel: '.exe, .dll',
    roadmap: ['Headers', 'Imports'],
    liveMessage: 'Soon this tool will be live',
  },
  'wav-spectrum-viewer': {
    slug: 'wav-spectrum-viewer',
    title: 'WAV Spectrum Viewer',
    tagline: 'Audio spectrum / waveform.',
    formatsLabel: '.wav',
    roadmap: ['Waveform', 'FFT'],
    liveMessage: 'Soon this tool will be live',
  },
  'spectrogram-viewer': {
    slug: 'spectrogram-viewer',
    title: 'Spectrogram Viewer',
    tagline: 'Spectrogram visualization.',
    formatsLabel: 'audio files',
    roadmap: ['STFT', 'Zoom'],
    liveMessage: 'Soon this tool will be live',
  },
  'minecraft-world-viewer': {
    slug: 'minecraft-world-viewer',
    title: 'Minecraft World Viewer',
    tagline: 'World map preview.',
    formatsLabel: 'Minecraft worlds',
    roadmap: ['Chunks', 'Biomes'],
    liveMessage: 'Soon this tool will be live',
  },
  'unity-asset-viewer': {
    slug: 'unity-asset-viewer',
    title: 'Unity Asset Viewer',
    tagline: 'Unity asset peek.',
    formatsLabel: 'Unity assets',
    roadmap: ['Metadata', 'Preview'],
    liveMessage: 'Soon this tool will be live',
  },
  'game-save-viewer': {
    slug: 'game-save-viewer',
    title: 'Game Save Viewer',
    tagline: 'Game save structure explore.',
    formatsLabel: 'save files',
    roadmap: ['Slots', 'Fields'],
    liveMessage: 'Soon this tool will be live',
  },
  'nft-metadata-viewer': {
    slug: 'nft-metadata-viewer',
    title: 'NFT Metadata Viewer',
    tagline: 'NFT metadata inspection.',
    formatsLabel: 'NFT JSON',
    roadmap: ['Traits', 'Media links'],
    liveMessage: 'Soon this tool will be live',
  },
  'smart-contract-viewer': {
    slug: 'smart-contract-viewer',
    title: 'Smart Contract Viewer',
    tagline: 'Contract source / ABI browse.',
    formatsLabel: '.sol / ABI',
    roadmap: ['ABI', 'Methods'],
    liveMessage: 'Soon this tool will be live',
  },
  'invoice-data-viewer': {
    slug: 'invoice-data-viewer',
    title: 'Invoice Data Viewer',
    tagline: 'Invoice field exploration.',
    formatsLabel: 'invoice JSON/XML',
    roadmap: ['Line items', 'Totals'],
    liveMessage: 'Soon this tool will be live',
  },
  'audit-log-viewer': {
    slug: 'audit-log-viewer',
    title: 'Audit Log Viewer',
    tagline: 'Enterprise audit trails.',
    formatsLabel: 'audit exports',
    roadmap: ['Actors', 'Timeline'],
    liveMessage: 'Soon this tool will be live',
  },
  'figma-export-viewer': {
    slug: 'figma-export-viewer',
    title: 'Figma Export Viewer',
    tagline: 'Design export preview.',
    formatsLabel: 'Figma exports',
    roadmap: ['Frames', 'Assets'],
    liveMessage: 'Soon this tool will be live',
  },
  'sketch-file-viewer': {
    slug: 'sketch-file-viewer',
    title: 'Sketch File Viewer',
    tagline: 'Sketch document preview.',
    formatsLabel: '.sketch',
    roadmap: ['Pages', 'Symbols'],
    liveMessage: 'Soon this tool will be live',
  },
  'indesign-viewer': {
    slug: 'indesign-viewer',
    title: 'InDesign Viewer',
    tagline: 'InDesign package peek.',
    formatsLabel: '.indd / IDML',
    roadmap: ['Spreads', 'Stories'],
    liveMessage: 'Soon this tool will be live',
  },
};
