// AUTO-GENERATED from apps/tools-site/assets/icons/categories/*.svg
// Do not edit manually.

/** Tool/category icon slugs that exist on disk. */
export const AVAILABLE_TOOL_ICON_SLUGS: readonly string[] = [
  '3d-model-viewer-gltf-obj-stl-fbx',
  'add-signature',
  'add-watermark',
  'age-calculator',
  'annotate-pdf',
  'archive-viewer-zip-tar-gz',
  'audio-player',
  'audio-player-mp3-wav-ogg-flac',
  'audio-trimmer',
  'barcode-generator',
  'battery-status-viewer',
  'bmi-calculator',
  'border-radius-preview',
  'box-shadow-generator',
  'cad-viewers',
  'clipboard-history',
  'clipboard-viewer',
  'coin-toss-dice-roller',
  'color-picker',
  'compress-pdf',
  'cookie-editor',
  'cors-test-tool',
  'create-pdf-from-html',
  'credit-card-validator',
  'css-gradient-generator',
  'css-minifier',
  'csv-json-converter',
  'currency-converter',
  'data-explorers',
  'date-difference-calculator',
  'date-to-day-of-week',
  'delete-pdf-pages',
  'dev-design-tools',
  'device-orientation-logger',
  'diagram-viewers',
  'drawing-pad',
  'email-url-ip-checker',
  'excel-to-json',
  'excel-viewer-xls-xlsx-csv',
  'extract-pdf-pages',
  'favicon-generator',
  'file-code-tools',
  'file-metadata-viewer',
  'file-viewers',
  'fill-pdf-forms',
  'flashcard-quiz-generator',
  'flatten-pdf-forms',
  'font-file-previewer-ttf-otf-woff',
  'fraction-calculator',
  'fun-productivity-tools',
  'gis-viewers',
  'gradient-generator',
  'hash-generator',
  'hex-to-rgb-converter',
  'highlight-text',
  'html-entity-encoder',
  'html-minifier',
  'html-table-exporter',
  'html-table-to-json',
  'http-header-decoder',
  'http-request-generator',
  'image-color-tools',
  'image-compressor',
  'image-resizer',
  'image-to-base64',
  'image-to-text-ocr',
  'image-viewer-png-jpeg-jpg-gif-bmp-svg-webp',
  'interest-calculator',
  'javascript-minifier',
  'json-data-converters',
  'json-formatter-validator',
  'json-linter-viewer',
  'json-parser',
  'json-schema-validator',
  'jwt-decoder',
  'loan-emi-calculator',
  'log-file-viewer-analyzer',
  'lorem-ipsum-generator',
  'markdown-previewer',
  'markdown-to-html',
  'markdown-to-pdf',
  'media-audio-tools',
  'medical-viewers',
  'merge-pdfs',
  'ml-viewers',
  'mock-json-generator',
  'motivational-quote-generator',
  'network-speed-test',
  'network-viewers',
  'number-date-tools',
  'number-to-words',
  'palette-generator',
  'password-protect-pdf',
  'password-rule-validator',
  'password-strength-checker',
  'pdf-metadata-editor',
  'pdf-to-base64',
  'pdf-tools',
  'pdf-viewer',
  'percentage-calculator',
  'pixel-to-rem-converter',
  'pomodoro-timer',
  'postman-lite',
  'powerpoint-viewer-ppt-pptx',
  'private-notes',
  'process-viewers',
  'qr-code-generator',
  'random-number-generator',
  'random-password-generator',
  'reorder-pdf-pages',
  'responsive-breakpoint-tester',
  'resume-invoice-generator',
  'rotate-pdf-pages',
  'science-viewers',
  'screen-resolution-info',
  'screenshot-to-pdf',
  'secure-clipboard',
  'security-crypto-tools',
  'split-pdfs',
  'stopwatch-timer',
  'storage-viewer',
  'system-browser-utilities',
  'tables-charts-to-pdf',
  'text-encrypt-decrypt',
  'text-file-viewer-txt-log-md-json-xml-yaml',
  'text-to-pdf',
  'text-utilities',
  'timezone-converter',
  'tip-calculator',
  'typing-speed-test',
  'unit-converter',
  'user-agent-parser',
  'uuid-generator',
  'validation-testing-tools',
  'video-player-mp4-webm-ogv',
  'video-to-gif-converter',
  'viewport-size-detector',
  'voice-recorder',
  'webcam-snapshot',
  'websocket-client',
  'word-document-viewer-doc-docx',
  'yaml-json-converter',
  'zodiac-finder',
];

/** Map tool path slug → category slug when known from catalog. */
export const TOOL_ICON_CATEGORY: Readonly<Record<string, string>> = {
  'add-signature': 'pdf-tools',
  'add-watermark': 'pdf-tools',
  'age-calculator': 'math-date-utils',
  'annotate-pdf': 'pdf-tools',
  'audio-player': 'media-tools',
  'audio-trimmer': 'media-tools',
  'barcode-generator': 'fun-tools',
  'battery-status-viewer': 'browser-utils',
  'bmi-calculator': 'math-date-utils',
  'border-radius-preview': 'dev-design-tools',
  'box-shadow-generator': 'dev-design-tools',
  'clipboard-history': 'code-file-tools',
  'clipboard-viewer': 'code-file-tools',
  'coin-toss-dice-roller': 'fun-tools',
  'color-picker': 'image-color-tools',
  'compress-pdf': 'pdf-tools',
  'cookie-editor': 'browser-utils',
  'cors-test-tool': 'dev-design-tools',
  'create-pdf-from-html': 'pdf-tools',
  'credit-card-validator': 'testing-tools',
  'css-gradient-generator': 'dev-design-tools',
  'css-minifier': 'code-file-tools',
  'currency-converter': 'math-date-utils',
  'date-difference-calculator': 'math-date-utils',
  'date-to-day-of-week': 'math-date-utils',
  'device-orientation-logger': 'browser-utils',
  'drawing-pad': 'image-color-tools',
  'email-url-ip-checker': 'testing-tools',
  'excel-to-json': 'data-converters',
  'favicon-generator': 'image-color-tools',
  'file-metadata-viewer': 'code-file-tools',
  'fill-pdf-forms': 'pdf-tools',
  'flashcard-quiz-generator': 'fun-tools',
  'flatten-pdf-forms': 'pdf-tools',
  'fraction-calculator': 'math-date-utils',
  'gradient-generator': 'image-color-tools',
  'hash-generator': 'security-tools',
  'highlight-text': 'pdf-tools',
  'html-entity-encoder': 'code-file-tools',
  'html-minifier': 'code-file-tools',
  'html-table-exporter': 'code-file-tools',
  'html-table-to-json': 'data-converters',
  'http-header-decoder': 'dev-design-tools',
  'http-request-generator': 'dev-design-tools',
  'image-compressor': 'image-color-tools',
  'image-resizer': 'image-color-tools',
  'image-to-base64': 'image-color-tools',
  'javascript-minifier': 'code-file-tools',
  'json-linter-viewer': 'data-converters',
  'json-parser': 'data-converters',
  'json-schema-validator': 'testing-tools',
  'jwt-decoder': 'testing-tools',
  'loan-emi-calculator': 'math-date-utils',
  'lorem-ipsum-generator': 'fun-tools',
  'markdown-previewer': 'file-viewers',
  'markdown-to-html': 'data-converters',
  'markdown-to-pdf': 'code-file-tools',
  'merge-pdfs': 'pdf-tools',
  'mock-json-generator': 'dev-design-tools',
  'motivational-quote-generator': 'fun-tools',
  'network-speed-test': 'browser-utils',
  'number-to-words': 'math-date-utils',
  'palette-generator': 'image-color-tools',
  'password-protect-pdf': 'pdf-tools',
  'password-rule-validator': 'testing-tools',
  'password-strength-checker': 'security-tools',
  'pdf-metadata-editor': 'pdf-tools',
  'pdf-to-base64': 'pdf-tools',
  'pdf-viewer': 'pdf-tools',
  'percentage-calculator': 'math-date-utils',
  'pomodoro-timer': 'fun-tools',
  'postman-lite': 'dev-design-tools',
  'private-notes': 'security-tools',
  'qr-code-generator': 'fun-tools',
  'random-number-generator': 'fun-tools',
  'random-password-generator': 'security-tools',
  'responsive-breakpoint-tester': 'dev-design-tools',
  'resume-invoice-generator': 'pdf-tools',
  'screen-resolution-info': 'browser-utils',
  'screenshot-to-pdf': 'pdf-tools',
  'secure-clipboard': 'security-tools',
  'split-pdfs': 'pdf-tools',
  'stopwatch-timer': 'fun-tools',
  'storage-viewer': 'browser-utils',
  'tables-charts-to-pdf': 'pdf-tools',
  'text-encrypt-decrypt': 'security-tools',
  'text-to-pdf': 'pdf-tools',
  'timezone-converter': 'fun-tools',
  'tip-calculator': 'math-date-utils',
  'typing-speed-test': 'fun-tools',
  'unit-converter': 'math-date-utils',
  'user-agent-parser': 'testing-tools',
  'uuid-generator': 'security-tools',
  'viewport-size-detector': 'dev-design-tools',
  'voice-recorder': 'media-tools',
  'webcam-snapshot': 'media-tools',
  'websocket-client': 'dev-design-tools',
  'zodiac-finder': 'math-date-utils',
};

