// AUTO-GENERATED — do not edit manually.
// Regenerate: node apps/tools-site/scripts/generate-tool-seo-catalog.js

export interface ToolSeoEntry {
  name: string;
  category: string;
  categorySlug: string;
  title: string;
  description: string;
  keywords: string;
}

export const TOOL_SEO_CATALOG: Record<string, ToolSeoEntry> = {
  '/tools/home': {
    name: 'EasyToolHub',
    category: 'Home',
    categorySlug: 'home',
    title: 'EasyToolHub - Free Online Tools for Everyone',
    description: 'Discover 160+ free online tools for text editing, PDF editing, file conversion, image tools, calculators, developer utilities, and security. No signup — fast, private, and browser-based.',
    keywords: 'free online tools, online utilities, text tools, PDF tools, file converter, image tools, JSON formatter, developer tools, password generator, QR code generator, unit converter, hash generator, word counter, merge PDF, compress PDF, easytoolhub',
  },
  '/text-utilities/character-counter': {
    name: 'Word & Character Counter',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Word & Character Counter - Free Online Text & Utilities Tool',
    description: 'Measure characters, words, reading time, and more in real time. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'word & character counter, word & character counter online, free word & character counter, character counter, text tool, text editor online, string utility, word counter, character count, letter counter, sentence counter, reading time calculator, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/text-case-convertor': {
    name: 'Text Case Converter',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Text Case Converter - Free Online Text & Utilities Tool',
    description: 'Switch text between lowercase, uppercase, sentence case, or custom formats. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'text case converter, text case converter online, free text case converter, text case convertor, text case, case convertor, text tool, text editor online, string utility, uppercase converter, lowercase converter, title case, sentence case, camel case converter, free online tool, no signup',
  },
  '/text-utilities/text-to-ascii': {
    name: 'Text to ASCII Converter',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Text to ASCII Converter - Free Online Text & Utilities Tool',
    description: 'Transform any text into ASCII codes for encoding or debugging. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'text to ascii converter, text to ascii converter online, free text to ascii converter, text ascii, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/remove-duplicate-lines': {
    name: 'Remove Duplicate Lines',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Remove Duplicate Lines - Free Online Text & Utilities Tool',
    description: 'Clean up repeated lines from pasted text while keeping order intact. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'remove duplicate lines, remove duplicate lines online, free remove duplicate lines, remove duplicate, duplicate lines, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/text-reversal-and-palindrome-checker': {
    name: 'Reverse Text & Palindrome Checker',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Reverse Text & Palindrome Checker - Free Online Tool',
    description: 'Flip strings instantly and verify whether phrases read the same both ways. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'reverse text & palindrome checker, reverse text & palindrome checker online, free reverse text & palindrome checker, text reversal palindrome checker, text reversal, reversal palindrome, palindrome checker, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/base64-encode-and-decode': {
    name: 'Base64 Encode & Decode',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Base64 Encode & Decode - Free Online Text & Utilities Tool',
    description: 'Encode files or strings to Base64 and decode them back effortlessly. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'base64 encode & decode, base64 encode & decode online, free base64 encode & decode, base64 encode decode, base64 encode, encode decode, text tool, text editor online, string utility, base64 encoder, base64 decoder, encode base64 online, decode base64, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/slug-generator': {
    name: 'Slug Generator',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Slug Generator - Free Online Text & Utilities Tool',
    description: 'Convert titles into clean, SEO-friendly URL slugs with smart formatting. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'slug generator, slug generator online, free slug generator, text tool, text editor online, string utility, url slug generator, seo slug, permalink generator, slugify, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/text-difference': {
    name: 'Text Difference Checker',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Text Difference Checker - Free Online Text & Utilities Tool',
    description: 'Compare two blocks of text and highlight additions, removals, or edits. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'text difference checker, text difference checker online, free text difference checker, text difference, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/code-merge': {
    name: 'Code Merge',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Code Merge - Free Online Text & Utilities Tool',
    description: 'Merge and reconcile code snippets with a clear diff-aware editor. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'code merge, code merge online, free code merge, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/url-encode-and-decode': {
    name: 'URL Encode & Decode',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'URL Encode & Decode - Free Online Text & Utilities Tool',
    description: 'Percent-encode or decode URL strings, query values, and Unicode text. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'url encode & decode, url encode & decode online, free url encode & decode, url encode decode, url encode, encode decode, text tool, text editor online, string utility, url encoder, url decoder, percent encode, decode url online, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/unicode-escape-unescape': {
    name: 'Unicode Escape & Unescape',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Unicode Escape & Unescape - Free Online Tool',
    description: 'Convert text to \\\\uXXXX escape sequences and back for debugging. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'unicode escape & unescape, unicode escape & unescape online, free unicode escape & unescape, unicode escape unescape, unicode escape, escape unescape, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/html-tag-stripper': {
    name: 'HTML Tag Stripper',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'HTML Tag Stripper - Free Online Text & Utilities Tool',
    description: 'Remove HTML markup and get clean plain text instantly. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'html tag stripper, html tag stripper online, free html tag stripper, html tag, tag stripper, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/sort-lines': {
    name: 'Sort Lines',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Sort Lines - Free Online Text & Utilities Tool',
    description: 'Sort lines alphabetically, by length, or numerically. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'sort lines, sort lines online, free sort lines, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/trim-normalize-whitespace': {
    name: 'Trim & Normalize Whitespace',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Trim & Normalize Whitespace - Free Online Tool',
    description: 'Trim lines, collapse spaces, and remove empty lines. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'trim & normalize whitespace, trim & normalize whitespace online, free trim & normalize whitespace, trim normalize whitespace, trim normalize, normalize whitespace, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/find-and-replace': {
    name: 'Find & Replace',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Find & Replace - Free Online Text & Utilities Tool',
    description: 'Search and replace text with plain or regex patterns. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'find & replace, find & replace online, free find & replace, find replace, text tool, text editor online, string utility, find and replace online, text replace, regex replace, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/line-number-tool': {
    name: 'Line Number Tool',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Line Number Tool - Free Online Text & Utilities Tool',
    description: 'Add or remove line numbers from any text block. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'line number tool, line number tool online, free line number tool, line number, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/split-join-text': {
    name: 'Split & Join Text',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Split & Join Text - Free Online Text & Utilities Tool',
    description: 'Split by delimiter or join lines with a custom separator. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'split & join text, split & join text online, free split & join text, split join text, split join, join text, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/regex-tester': {
    name: 'Regex Tester',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Regex Tester - Free Online Text & Utilities Tool',
    description: 'Test regular expressions and view matches in real time. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'regex tester, regex tester online, free regex tester, text tool, text editor online, string utility, regular expression tester, regex match, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/text-similarity': {
    name: 'Text Similarity Checker',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Text Similarity Checker - Free Online Text & Utilities Tool',
    description: 'Compare two strings with Levenshtein distance and similarity score. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'text similarity checker, text similarity checker online, free text similarity checker, text similarity, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/invisible-character-detector': {
    name: 'Invisible Character Detector',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Invisible Character Detector - Free Online Tool',
    description: 'Find zero-width spaces and hidden Unicode characters. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'invisible character detector, invisible character detector online, free invisible character detector, invisible character, character detector, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/word-wrap-unwrap': {
    name: 'Word Wrap & Unwrap',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Word Wrap & Unwrap - Free Online Text & Utilities Tool',
    description: 'Wrap text at a column width or unwrap hard line breaks. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'word wrap & unwrap, word wrap & unwrap online, free word wrap & unwrap, word wrap unwrap, word wrap, wrap unwrap, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/extract-emails-urls': {
    name: 'Extract Emails & URLs',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Extract Emails & URLs - Free Online Text & Utilities Tool',
    description: 'Pull email addresses and links from any text blob. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'extract emails & urls, extract emails & urls online, free extract emails & urls, extract emails urls, extract emails, emails urls, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/json-string-escape-unescape': {
    name: 'JSON String Escape & Unescape',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'JSON String Escape & Unescape - Free Online Tool',
    description: 'Escape or unescape strings for safe JSON embedding. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'json string escape & unescape, json string escape & unescape online, free json string escape & unescape, json string escape unescape, json string, string escape, escape unescape, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/hex-encode-decode': {
    name: 'Hex Encode & Decode',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Hex Encode & Decode - Free Online Text & Utilities Tool',
    description: 'Convert text to hexadecimal and decode hex to text. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'hex encode & decode, hex encode & decode online, free hex encode & decode, hex encode decode, hex encode, encode decode, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/rot13-cipher': {
    name: 'ROT13 & Caesar Cipher',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'ROT13 & Caesar Cipher - Free Online Text & Utilities Tool',
    description: 'Apply ROT13 or custom Caesar cipher shifts to text. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'rot13 & caesar cipher, rot13 & caesar cipher online, free rot13 & caesar cipher, rot13 cipher, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/binary-text-converter': {
    name: 'Binary Text Converter',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Binary Text Converter - Free Online Text & Utilities Tool',
    description: 'Convert text to binary and decode binary back to text. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'binary text converter, binary text converter online, free binary text converter, binary text, text converter, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/morse-code-converter': {
    name: 'Morse Code Converter',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Morse Code Converter - Free Online Text & Utilities Tool',
    description: 'Encode text to Morse code and decode it back. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'morse code converter, morse code converter online, free morse code converter, morse code, code converter, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/readability-analyzer': {
    name: 'Readability Analyzer',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Readability Analyzer - Free Online Text & Utilities Tool',
    description: 'Get Flesch Reading Ease and grade-level scores for any text. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'readability analyzer, readability analyzer online, free readability analyzer, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/keyword-density': {
    name: 'Keyword Density Checker',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Keyword Density Checker - Free Online Text & Utilities Tool',
    description: 'Analyze word frequency and keyword density for SEO. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'keyword density checker, keyword density checker online, free keyword density checker, keyword density, text tool, text editor online, string utility, seo keyword analyzer, word frequency, free online tool, no signup, easytoolhub',
  },
  '/text-utilities/pako-encode-and-decode': {
    name: 'Pako Compress & Decompress',
    category: 'Text & Utilities',
    categorySlug: 'text-utilities',
    title: 'Pako Compress & Decompress - Free Online Tool',
    description: 'Compress or decompress text with zlib deflate, raw deflate, or gzip. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'pako compress & decompress, pako compress & decompress online, free pako compress & decompress, pako encode decode, pako encode, encode decode, text tool, text editor online, string utility, free online tool, no signup, easytoolhub',
  },
  '/file-viewers/image-viewer': {
    name: 'Image Viewer',
    category: 'File Viewers',
    categorySlug: 'file-viewers',
    title: 'Image Viewer - Free Online File Viewers Tool',
    description: 'Preview formats from PNG to WebP without plugins. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'image viewer, image viewer online, free image viewer, file viewer online, document viewer, open file in browser, free online tool, no signup, easytoolhub',
  },
  '/file-viewers/pdf-viewer': {
    name: 'PDF Viewer',
    category: 'File Viewers',
    categorySlug: 'file-viewers',
    title: 'PDF Viewer - Free Online File Viewers Tool',
    description: 'Navigate documents with tabs, outlines, and zoom. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'pdf viewer, pdf viewer online, free pdf viewer, file viewer online, document viewer, open file in browser, free online tool, no signup, easytoolhub',
  },
  '/file-viewers/word-viewer': {
    name: 'Word Viewer',
    category: 'File Viewers',
    categorySlug: 'file-viewers',
    title: 'Word Viewer - Free Online File Viewers Tool',
    description: 'Open and preview DOCX Word documents in your browser without installing Office. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'word viewer, word viewer online, free word viewer, file viewer online, document viewer, open file in browser, docx viewer, open word document online, microsoft word viewer, free online tool, no signup, easytoolhub',
  },
  '/file-viewers/powerpoint-viewer': {
    name: 'PowerPoint Viewer',
    category: 'File Viewers',
    categorySlug: 'file-viewers',
    title: 'PowerPoint Viewer - Free Online File Viewers Tool',
    description: 'Preview PPTX presentations online with slides, notes, and zoom controls. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'powerpoint viewer, powerpoint viewer online, free powerpoint viewer, file viewer online, document viewer, open file in browser, pptx viewer, open powerpoint online, presentation viewer, free online tool, no signup, easytoolhub',
  },
  '/file-viewers/text-file-viewer': {
    name: 'Text File Viewer',
    category: 'File Viewers',
    categorySlug: 'file-viewers',
    title: 'Text File Viewer - Free Online File Viewers Tool',
    description: 'Open TXT, LOG, and plain-text files with search, wrap, and encoding support. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'text file viewer, text file viewer online, free text file viewer, text file, file viewer, file viewer online, document viewer, open file in browser, txt viewer online, open text file, log file viewer, free online tool, no signup, easytoolhub',
  },
  '/file-viewers/markdown-previewer': {
    name: 'Markdown Previewer',
    category: 'File Viewers',
    categorySlug: 'file-viewers',
    title: 'Markdown Previewer - Free Online File Viewers Tool',
    description: 'Check headings, code blocks, and typography fast. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'markdown previewer, markdown previewer online, free markdown previewer, file viewer online, document viewer, open file in browser, free online tool, no signup, easytoolhub',
  },
  '/file-viewers/excel-viewer': {
    name: 'Excel Viewer',
    category: 'File Viewers',
    categorySlug: 'file-viewers',
    title: 'Excel Viewer - Free Online File Viewers Tool',
    description: 'Inspect spreadsheet cells, formulas, and sheets. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'excel viewer, excel viewer online, free excel viewer, file viewer online, document viewer, open file in browser, free online tool, no signup, easytoolhub',
  },
  '/file-viewers/log-viewer': {
    name: 'Log Viewer',
    category: 'File Viewers',
    categorySlug: 'file-viewers',
    title: 'Log Viewer - Free Online File Viewers Tool',
    description: 'Search and filter large logs in the browser. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'log viewer, log viewer online, free log viewer, file viewer online, document viewer, open file in browser, free online tool, no signup, easytoolhub',
  },
  '/file-viewers/audio-player': {
    name: 'Audio Player',
    category: 'File Viewers',
    categorySlug: 'file-viewers',
    title: 'Audio Player - Free Online File Viewers Tool',
    description: 'Stream and scrub audio files instantly. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'audio player, audio player online, free audio player, file viewer online, document viewer, open file in browser, free online tool, no signup, easytoolhub',
  },
  '/file-viewers/video-player': {
    name: 'Video Player',
    category: 'File Viewers',
    categorySlug: 'file-viewers',
    title: 'Video Player - Free Online File Viewers Tool',
    description: 'Review MP4, WEBM, and more with custom controls. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'video player, video player online, free video player, file viewer online, document viewer, open file in browser, free online tool, no signup, easytoolhub',
  },
  '/file-viewers/font-viewer': {
    name: 'Font Viewer',
    category: 'File Viewers',
    categorySlug: 'file-viewers',
    title: 'Font Viewer - Free Online File Viewers Tool',
    description: 'Audit glyph sets before you embed fonts. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'font viewer, font viewer online, free font viewer, file viewer online, document viewer, open file in browser, free online tool, no signup, easytoolhub',
  },
  '/file-viewers/3d-model-viewer': {
    name: '3D Model Viewer',
    category: 'File Viewers',
    categorySlug: 'file-viewers',
    title: '3D Model Viewer - Free Online File Viewers Tool',
    description: 'Inspect GLB, GLTF, and other 3D models with orbit, zoom, and lighting controls. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: '3d model viewer, 3d model viewer online, free 3d model viewer, 3d model, model viewer, file viewer online, document viewer, open file in browser, glb viewer, gltf viewer, 3d file viewer, free online tool, no signup, easytoolhub',
  },
  '/file-viewers/archive-viewer': {
    name: 'Archive Viewer',
    category: 'File Viewers',
    categorySlug: 'file-viewers',
    title: 'Archive Viewer - Free Online File Viewers Tool',
    description: 'Peek inside ZIP and TAR archives without extracting. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'archive viewer, archive viewer online, free archive viewer, file viewer online, document viewer, open file in browser, free online tool, no signup, easytoolhub',
  },
  '/data-converters/json-formatter-beautifier-validator': {
    name: 'JSON Formatter & Validator',
    category: 'JSON / Data Converters',
    categorySlug: 'data-converters',
    title: 'JSON Formatter & Validator - Free Online Tool',
    description: 'Beautify, validate, and explore structured payloads effortlessly. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'json formatter & validator, json formatter & validator online, free json formatter & validator, json formatter beautifier validator, json formatter, formatter beautifier, beautifier validator, data converter, format converter, json tools, json beautifier, json validator, pretty print json, json prettifier, free online tool, no signup',
  },
  '/data-converters/csv-to-json-json-to-csv': {
    name: 'CSV ↔ JSON',
    category: 'JSON / Data Converters',
    categorySlug: 'data-converters',
    title: 'CSV ↔ JSON - Free Online JSON / Data Converters Tool',
    description: 'Switch between spreadsheets and APIs instantly. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'csv ↔ json, csv ↔ json online, free csv ↔ json, csv json json csv, csv json, json json, json csv, data converter, format converter, json tools, csv to json, json to csv, convert csv json, free online tool, no signup, easytoolhub',
  },
  '/data-converters/yaml-to-json-json-to-yaml': {
    name: 'YAML ↔ JSON',
    category: 'JSON / Data Converters',
    categorySlug: 'data-converters',
    title: 'YAML ↔ JSON - Free Online JSON / Data Converters Tool',
    description: 'Keep configuration files in sync across systems. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'yaml ↔ json, yaml ↔ json online, free yaml ↔ json, yaml json json yaml, yaml json, json json, json yaml, data converter, format converter, json tools, yaml to json, json to yaml, yaml converter, free online tool, no signup, easytoolhub',
  },
  '/data-converters/html-table-to-json': {
    name: 'HTML Table → JSON',
    category: 'JSON / Data Converters',
    categorySlug: 'data-converters',
    title: 'HTML Table → JSON - Free Online JSON / Data Converters Tool',
    description: 'Turn tabular content into structured objects. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'html table → json, html table → json online, free html table → json, html table json, html table, table json, data converter, format converter, json tools, free online tool, no signup, easytoolhub',
  },
  '/data-converters/markdown-to-html': {
    name: 'Markdown → HTML',
    category: 'JSON / Data Converters',
    categorySlug: 'data-converters',
    title: 'Markdown → HTML - Free Online JSON / Data Converters Tool',
    description: 'Publish-ready markup from clean Markdown. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'markdown → html, markdown → html online, free markdown → html, markdown html, data converter, format converter, json tools, free online tool, no signup, easytoolhub',
  },
  '/data-converters/json-linter-viewer': {
    name: 'JSON Linter Viewer',
    category: 'JSON / Data Converters',
    categorySlug: 'data-converters',
    title: 'JSON Linter Viewer - Free Online JSON / Data Converters Tool',
    description: 'Surface syntax errors with contextual guidance. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'json linter viewer, json linter viewer online, free json linter viewer, json linter, linter viewer, data converter, format converter, json tools, free online tool, no signup, easytoolhub',
  },
  '/data-converters/excel-to-json': {
    name: 'Excel → JSON',
    category: 'JSON / Data Converters',
    categorySlug: 'data-converters',
    title: 'Excel → JSON - Free Online JSON / Data Converters Tool',
    description: 'Upload spreadsheets and export structured data. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'excel → json, excel → json online, free excel → json, excel json, data converter, format converter, json tools, free online tool, no signup, easytoolhub',
  },
  '/data-converters/json-parser': {
    name: 'JSON Parser & Explorer',
    category: 'JSON / Data Converters',
    categorySlug: 'data-converters',
    title: 'JSON Parser & Explorer - Free Online Tool',
    description: 'Navigate nested structures with a live tree view. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'json parser & explorer, json parser & explorer online, free json parser & explorer, json parser, data converter, format converter, json tools, free online tool, no signup, easytoolhub',
  },
  '/math-date-utils/unit-converter': {
    name: 'Unit Converter',
    category: 'Number & Date Tools',
    categorySlug: 'math-date-utils',
    title: 'Unit Converter - Free Online Number & Date Tools Tool',
    description: 'Go between metric, imperial, and scientific units quickly. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'unit converter, unit converter online, free unit converter, calculator online, converter tool, math utility, metric converter, length weight converter, free online tool, no signup, easytoolhub',
  },
  '/math-date-utils/number-to-words': {
    name: 'Number to Words Converter',
    category: 'Number & Date Tools',
    categorySlug: 'math-date-utils',
    title: 'Number to Words Converter - Free Online Tool',
    description: 'Convert numbers into written words for checks, invoices, and documents. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'number to words converter, number to words converter online, free number to words converter, number words, calculator online, converter tool, math utility, number to words, numbers to words converter, convert number to text, cheque amount in words, free online tool, no signup, easytoolhub',
  },
  '/math-date-utils/percentage-calculator': {
    name: 'Percentage Calculator',
    category: 'Number & Date Tools',
    categorySlug: 'math-date-utils',
    title: 'Percentage Calculator - Free Online Number & Date Tools Tool',
    description: 'Solve increase, decrease, and proportion questions. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'percentage calculator, percentage calculator online, free percentage calculator, calculator online, converter tool, math utility, free online tool, no signup, easytoolhub',
  },
  '/math-date-utils/age-calculator': {
    name: 'Age Calculator',
    category: 'Number & Date Tools',
    categorySlug: 'math-date-utils',
    title: 'Age Calculator - Free Online Number & Date Tools Tool',
    description: 'Compute birthdays and anniversaries accurately. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'age calculator, age calculator online, free age calculator, calculator online, converter tool, math utility, calculate age from date of birth, free online tool, no signup, easytoolhub',
  },
  '/math-date-utils/date-difference-calculator': {
    name: 'Date Difference',
    category: 'Number & Date Tools',
    categorySlug: 'math-date-utils',
    title: 'Date Difference - Free Online Number & Date Tools Tool',
    description: 'Count days, weeks, or months between key events. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'date difference, date difference online, free date difference, date difference calculator, difference calculator, calculator online, converter tool, math utility, free online tool, no signup, easytoolhub',
  },
  '/math-date-utils/simple-compound-interest-calculator': {
    name: 'Simple & Compound Interest',
    category: 'Number & Date Tools',
    categorySlug: 'math-date-utils',
    title: 'Simple & Compound Interest - Free Online Tool',
    description: 'Model returns across time horizons. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'simple & compound interest, simple & compound interest online, free simple & compound interest, simple compound interest calculator, simple compound, compound interest, interest calculator, calculator online, converter tool, math utility, free online tool, no signup, easytoolhub',
  },
  '/math-date-utils/bmi-calculator': {
    name: 'BMI Calculator',
    category: 'Number & Date Tools',
    categorySlug: 'math-date-utils',
    title: 'BMI Calculator - Free Online Number & Date Tools Tool',
    description: 'Calculate body mass index from height and weight with clear category results. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'bmi calculator, bmi calculator online, free bmi calculator, calculator online, converter tool, math utility, body mass index calculator, calculate bmi online, bmi chart, free online tool, no signup, easytoolhub',
  },
  '/math-date-utils/loan-emi-calculator': {
    name: 'Loan EMI Calculator',
    category: 'Number & Date Tools',
    categorySlug: 'math-date-utils',
    title: 'Loan EMI Calculator - Free Online Number & Date Tools Tool',
    description: 'Project repayments for mortgages and loans. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'loan emi calculator, loan emi calculator online, free loan emi calculator, loan emi, emi calculator, calculator online, converter tool, math utility, loan calculator, monthly emi, free online tool, no signup, easytoolhub',
  },
  '/math-date-utils/tip-calculator': {
    name: 'Tip Calculator',
    category: 'Number & Date Tools',
    categorySlug: 'math-date-utils',
    title: 'Tip Calculator - Free Online Number & Date Tools Tool',
    description: 'Split bills fairly with friends or teams. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'tip calculator, tip calculator online, free tip calculator, calculator online, converter tool, math utility, free online tool, no signup, easytoolhub',
  },
  '/math-date-utils/currency-converter': {
    name: 'Currency Converter',
    category: 'Number & Date Tools',
    categorySlug: 'math-date-utils',
    title: 'Currency Converter - Free Online Number & Date Tools Tool',
    description: 'Check live conversion rates for common currencies. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'currency converter, currency converter online, free currency converter, calculator online, converter tool, math utility, exchange rate calculator, free online tool, no signup, easytoolhub',
  },
  '/math-date-utils/fraction-calculator': {
    name: 'Fraction Calculator',
    category: 'Number & Date Tools',
    categorySlug: 'math-date-utils',
    title: 'Fraction Calculator - Free Online Number & Date Tools Tool',
    description: 'Add, subtract, multiply, and divide fractions with simplified results. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'fraction calculator, fraction calculator online, free fraction calculator, calculator online, converter tool, math utility, add fractions, simplify fractions, fraction solver, free online tool, no signup, easytoolhub',
  },
  '/math-date-utils/date-to-day-of-week': {
    name: 'Date to Day of Week',
    category: 'Number & Date Tools',
    categorySlug: 'math-date-utils',
    title: 'Date to Day of Week - Free Online Number & Date Tools Tool',
    description: 'Find which weekday any date falls on — past, present, or future. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'date to day of week, date to day of week online, free date to day of week, date day week, date day, day week, calculator online, converter tool, math utility, what day is this date, day of week calculator, date to weekday, calendar day finder, free online tool, no signup, easytoolhub',
  },
  '/math-date-utils/zodiac-finder': {
    name: 'Zodiac Finder',
    category: 'Number & Date Tools',
    categorySlug: 'math-date-utils',
    title: 'Zodiac Finder - Free Online Number & Date Tools Tool',
    description: 'Discover astrological signs from any date. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'zodiac finder, zodiac finder online, free zodiac finder, calculator online, converter tool, math utility, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/pdf-viewer': {
    name: 'PDF Studio',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'PDF Studio - Free Online PDF Tools Tool',
    description: 'View, edit, and optimise PDF documents end-to-end. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'pdf studio, pdf studio online, free pdf studio, pdf viewer, pdf tool online, edit pdf free, pdf utility, pdf viewer online, view pdf in browser, free pdf reader, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/merge-pdfs': {
    name: 'Merge PDFs',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Merge PDFs - Free Online PDF Tools Tool',
    description: 'Combine files into a single deliverable. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'merge pdfs, merge pdfs online, free merge pdfs, pdf tool online, edit pdf free, pdf utility, merge pdf, combine pdf, pdf merger, join pdf files, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/split-pdfs': {
    name: 'Split PDFs',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Split PDFs - Free Online PDF Tools Tool',
    description: 'Extract specific ranges into new documents. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'split pdfs, split pdfs online, free split pdfs, pdf tool online, edit pdf free, pdf utility, split pdf, pdf splitter, separate pdf pages, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/delete-pages': {
    name: 'Delete PDF Pages',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Delete PDF Pages - Free Online PDF Tools Tool',
    description: 'Remove unwanted pages from a PDF instantly. Files stay private in your browser. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'delete pdf pages, delete pdf pages online, free delete pdf pages, delete pages, pdf tool online, edit pdf free, pdf utility, remove pages from pdf, pdf page remover, drop pdf pages, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/rotate-pages': {
    name: 'Rotate PDF Pages',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Rotate PDF Pages - Free Online PDF Tools Tool',
    description: 'Rotate PDF pages 90°, 180°, or 270° and save a corrected document. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'rotate pdf pages, rotate pdf pages online, free rotate pdf pages, rotate pages, pdf tool online, edit pdf free, pdf utility, rotate pdf, fix sideways pdf, pdf page rotator, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/reorder-pages': {
    name: 'Reorder PDF Pages',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Reorder PDF Pages - Free Online PDF Tools Tool',
    description: 'Drag and rearrange PDF page order before downloading the new file. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'reorder pdf pages, reorder pdf pages online, free reorder pdf pages, reorder pages, pdf tool online, edit pdf free, pdf utility, rearrange pdf, change pdf page order, organize pdf pages, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/extract-pages': {
    name: 'Extract PDF Pages',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Extract PDF Pages - Free Online PDF Tools Tool',
    description: 'Pull selected pages into a new PDF without uploading to a server. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'extract pdf pages, extract pdf pages online, free extract pdf pages, extract pages, pdf tool online, edit pdf free, pdf utility, save pages from pdf, pdf page extractor, split pages from pdf, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/compress-pdf': {
    name: 'Compress PDF',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Compress PDF - Free Online PDF Tools Tool',
    description: 'Reduce file size for quicker sharing. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'compress pdf, compress pdf online, free compress pdf, pdf tool online, edit pdf free, pdf utility, reduce pdf size, pdf compressor online, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/create-pdf-from-html': {
    name: 'Create PDF from HTML',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Create PDF from HTML - Free Online PDF Tools Tool',
    description: 'Export responsive pages into accessible PDFs. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'create pdf from html, create pdf from html online, free create pdf from html, create pdf html, create pdf, pdf html, pdf tool online, edit pdf free, pdf utility, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/tables-charts-to-pdf': {
    name: 'Tables & Charts to PDF',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Tables & Charts to PDF - Free Online PDF Tools Tool',
    description: 'Turn tables and charts into clean, printable PDF documents. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'tables & charts to pdf, tables & charts to pdf online, free tables & charts to pdf, tables charts pdf, tables charts, charts pdf, pdf tool online, edit pdf free, pdf utility, table to pdf, chart to pdf, export table pdf, convert chart to pdf, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/resume-invoice-generator': {
    name: 'Resume & Invoice Generator',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Resume & Invoice Generator - Free Online PDF Tools Tool',
    description: 'Build professional docs with guided templates. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'resume & invoice generator, resume & invoice generator online, free resume & invoice generator, resume invoice generator, resume invoice, invoice generator, pdf tool online, edit pdf free, pdf utility, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/text-to-pdf': {
    name: 'Text to PDF',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Text to PDF - Free Online PDF Tools Tool',
    description: 'Convert plain text into a formatted PDF document. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'text to pdf, text to pdf online, free text to pdf, text pdf, pdf tool online, edit pdf free, pdf utility, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/screenshot-to-pdf': {
    name: 'Screenshot to PDF',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Screenshot to PDF - Free Online PDF Tools Tool',
    description: 'Convert screenshots and images into a multi-page PDF in seconds. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'screenshot to pdf, screenshot to pdf online, free screenshot to pdf, screenshot pdf, pdf tool online, edit pdf free, pdf utility, image screenshot pdf, convert screenshot pdf, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/annotate-pdf': {
    name: 'Annotate PDF',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Annotate PDF - Free Online PDF Tools Tool',
    description: 'Add notes, markup, and comments to PDF pages in your browser. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'annotate pdf, annotate pdf online, free annotate pdf, pdf tool online, edit pdf free, pdf utility, pdf markup, comment on pdf, pdf annotation tool, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/highlight-text': {
    name: 'Highlight PDF Text',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Highlight PDF Text - Free Online PDF Tools Tool',
    description: 'Highlight important text in PDFs and export the marked-up file. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'highlight pdf text, highlight pdf text online, free highlight pdf text, highlight text, pdf tool online, edit pdf free, pdf utility, highlight pdf, pdf highlighter, mark text in pdf, highlight pdf online, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/add-signature': {
    name: 'Add Signature to PDF',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Add Signature to PDF - Free Online PDF Tools Tool',
    description: 'Draw or upload a signature and place it on any PDF page. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'add signature to pdf, add signature to pdf online, free add signature to pdf, add signature, pdf tool online, edit pdf free, pdf utility, sign pdf online, electronic signature pdf, pdf signer, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/fill-pdf-forms': {
    name: 'Fill PDF Forms',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Fill PDF Forms - Free Online PDF Tools Tool',
    description: 'Complete form fields and save persistently. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'fill pdf forms, fill pdf forms online, free fill pdf forms, fill pdf, pdf forms, pdf tool online, edit pdf free, pdf utility, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/pdf-metadata-editor': {
    name: 'PDF Metadata Editor',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'PDF Metadata Editor - Free Online PDF Tools Tool',
    description: 'Edit PDF title, author, subject, and keywords without desktop software. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'pdf metadata editor, pdf metadata editor online, free pdf metadata editor, pdf metadata, metadata editor, pdf tool online, edit pdf free, pdf utility, edit pdf properties, pdf title author, change pdf metadata, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/add-watermark': {
    name: 'Add Watermark',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Add Watermark - Free Online PDF Tools Tool',
    description: 'Brand documents before distribution. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'add watermark, add watermark online, free add watermark, pdf tool online, edit pdf free, pdf utility, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/pdf-to-base64': {
    name: 'PDF to Base64',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'PDF to Base64 - Free Online PDF Tools Tool',
    description: 'Encode a PDF as Base64 for APIs, embeds, and data URLs — or decode back. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'pdf to base64, pdf to base64 online, free pdf to base64, pdf base64, pdf tool online, edit pdf free, pdf utility, encode pdf base64, base64 pdf converter, pdf data uri, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/password-protect-pdf': {
    name: 'PDF Password Protect',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'PDF Password Protect - Free Online PDF Tools Tool',
    description: 'Lock sensitive documents before you share them. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'pdf password protect, pdf password protect online, free pdf password protect, password protect pdf, password protect, protect pdf, pdf tool online, edit pdf free, pdf utility, encrypt pdf, lock pdf, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/flatten-pdf-forms': {
    name: 'Flatten PDF Forms',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Flatten PDF Forms - Free Online PDF Tools Tool',
    description: 'Flatten fillable PDF form fields into a non-editable document. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'flatten pdf forms, flatten pdf forms online, free flatten pdf forms, flatten pdf, pdf forms, pdf tool online, edit pdf free, pdf utility, flatten pdf form, flatten pdf fields, make pdf non editable, pdf form flattener, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/html-to-pdf': {
    name: 'HTML to PDF',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'HTML to PDF - Free Online PDF Tools Tool',
    description: 'Render HTML with styles and export a print-ready PDF. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'html to pdf, html to pdf online, free html to pdf, html pdf, pdf tool online, edit pdf free, pdf utility, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/tables-to-pdf': {
    name: 'Tables to PDF',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Tables to PDF - Free Online PDF Tools Tool',
    description: 'Export editable tables into formatted PDF documents. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'tables to pdf, tables to pdf online, free tables to pdf, tables pdf, pdf tool online, edit pdf free, pdf utility, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/charts-to-pdf': {
    name: 'Charts to PDF',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Charts to PDF - Free Online PDF Tools Tool',
    description: 'Preview charts and export them to PDF. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'charts to pdf, charts to pdf online, free charts to pdf, charts pdf, pdf tool online, edit pdf free, pdf utility, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/resume-generator': {
    name: 'Resume Generator',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Resume Generator - Free Online PDF Tools Tool',
    description: 'Build a professional resume PDF from structured fields. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'resume generator, resume generator online, free resume generator, pdf tool online, edit pdf free, pdf utility, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/invoice-generator': {
    name: 'Invoice Generator',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Invoice Generator - Free Online PDF Tools Tool',
    description: 'Create invoices with line items, tax, and totals. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'invoice generator, invoice generator online, free invoice generator, pdf tool online, edit pdf free, pdf utility, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/image-to-pdf': {
    name: 'Image to PDF',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Image to PDF - Free Online PDF Tools Tool',
    description: 'Combine multiple images into a single PDF. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'image to pdf, image to pdf online, free image to pdf, image pdf, pdf tool online, edit pdf free, pdf utility, jpg to pdf, png to pdf, convert image pdf, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/add-page-numbers': {
    name: 'Add Page Numbers',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Add Page Numbers - Free Online PDF Tools Tool',
    description: 'Stamp page numbers with custom position and format. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'add page numbers, add page numbers online, free add page numbers, add page, page numbers, pdf tool online, edit pdf free, pdf utility, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/barcode-to-pdf': {
    name: 'Barcode to PDF',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'Barcode to PDF - Free Online PDF Tools Tool',
    description: 'Generate a barcode inside a PDF document. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'barcode to pdf, barcode to pdf online, free barcode to pdf, barcode pdf, pdf tool online, edit pdf free, pdf utility, free online tool, no signup, easytoolhub',
  },
  '/pdf-tools/qr-code-to-pdf': {
    name: 'QR Code to PDF',
    category: 'PDF Tools',
    categorySlug: 'pdf-tools',
    title: 'QR Code to PDF - Free Online PDF Tools Tool',
    description: 'Generate a QR code inside a PDF document. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'qr code to pdf, qr code to pdf online, free qr code to pdf, qr code pdf, qr code, code pdf, pdf tool online, edit pdf free, pdf utility, free online tool, no signup, easytoolhub',
  },
  '/image-color-tools/image-to-base64': {
    name: 'Image to Base64',
    category: 'Image & Color Tools',
    categorySlug: 'image-color-tools',
    title: 'Image to Base64 - Free Online Image & Color Tools Tool',
    description: 'Convert images to embeddable Base64 strings. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'image to base64, image to base64 online, free image to base64, image base64, image tool online, photo editor utility, color tool, free online tool, no signup, easytoolhub',
  },
  '/image-color-tools/image-resizer': {
    name: 'Image Resizer',
    category: 'Image & Color Tools',
    categorySlug: 'image-color-tools',
    title: 'Image Resizer - Free Online Image & Color Tools Tool',
    description: 'Crop and scale assets with pixel-perfect control. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'image resizer, image resizer online, free image resizer, image tool online, photo editor utility, color tool, resize photo online, change image size, free online tool, no signup, easytoolhub',
  },
  '/image-color-tools/image-compressor': {
    name: 'Image Compressor',
    category: 'Image & Color Tools',
    categorySlug: 'image-color-tools',
    title: 'Image Compressor - Free Online Image & Color Tools Tool',
    description: 'Optimise supporting media before publishing. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'image compressor, image compressor online, free image compressor, image tool online, photo editor utility, color tool, compress jpg, reduce image size, free online tool, no signup, easytoolhub',
  },
  '/image-color-tools/color-picker': {
    name: 'Color Picker',
    category: 'Image & Color Tools',
    categorySlug: 'image-color-tools',
    title: 'Color Picker - Free Online Image & Color Tools Tool',
    description: 'Sample, harmonise, and store brand colours. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'color picker, color picker online, free color picker, image tool online, photo editor utility, color tool, hex color picker, eyedropper tool, free online tool, no signup, easytoolhub',
  },
  '/image-color-tools/hex-to-rgb': {
    name: 'HEX ↔ RGB',
    category: 'Image & Color Tools',
    categorySlug: 'image-color-tools',
    title: 'HEX ↔ RGB - Free Online Image & Color Tools Tool',
    description: 'Translate colour models instantly. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'hex ↔ rgb, hex ↔ rgb online, free hex ↔ rgb, hex rgb, image tool online, photo editor utility, color tool, hex to rgb, rgb to hex, color converter, free online tool, no signup, easytoolhub',
  },
  '/image-color-tools/gradient-generator': {
    name: 'Gradient Generator',
    category: 'Image & Color Tools',
    categorySlug: 'image-color-tools',
    title: 'Gradient Generator - Free Online Image & Color Tools Tool',
    description: 'Design smooth gradients with CSS output. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'gradient generator, gradient generator online, free gradient generator, image tool online, photo editor utility, color tool, free online tool, no signup, easytoolhub',
  },
  '/image-color-tools/palette-generator': {
    name: 'Palette Generator',
    category: 'Image & Color Tools',
    categorySlug: 'image-color-tools',
    title: 'Palette Generator - Free Online Image & Color Tools Tool',
    description: 'Build colour systems from images and inspiration shots. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'palette generator, palette generator online, free palette generator, image tool online, photo editor utility, color tool, free online tool, no signup, easytoolhub',
  },
  '/image-color-tools/image-to-text': {
    name: 'Image to Text',
    category: 'Image & Color Tools',
    categorySlug: 'image-color-tools',
    title: 'Image to Text - Free Online Image & Color Tools Tool',
    description: 'Extract text from images with OCR — paste or upload and copy results. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'image to text, image to text online, free image to text, image text, image tool online, photo editor utility, color tool, ocr online, extract text from image, photo to text converter, free online tool, no signup, easytoolhub',
  },
  '/image-color-tools/favicon-generator': {
    name: 'Favicon Generator',
    category: 'Image & Color Tools',
    categorySlug: 'image-color-tools',
    title: 'Favicon Generator - Free Online Image & Color Tools Tool',
    description: 'Create multi-size favicons and manifest icons. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'favicon generator, favicon generator online, free favicon generator, image tool online, photo editor utility, color tool, free online tool, no signup, easytoolhub',
  },
  '/image-color-tools/drawing-pad': {
    name: 'Drawing Pad',
    category: 'Image & Color Tools',
    categorySlug: 'image-color-tools',
    title: 'Drawing Pad - Free Online Image & Color Tools Tool',
    description: 'Sketch UI ideas or annotate screenshots. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'drawing pad, drawing pad online, free drawing pad, image tool online, photo editor utility, color tool, free online tool, no signup, easytoolhub',
  },
  '/code-file-tools/html-minifier': {
    name: 'HTML Minifier',
    category: 'File & Code Tools',
    categorySlug: 'code-file-tools',
    title: 'HTML Minifier - Free Online File & Code Tools Tool',
    description: 'Reduce file size with whitespace-aware minification. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'html minifier, html minifier online, free html minifier, code tool online, developer utility, minify tool, minify html online, free online tool, no signup, easytoolhub',
  },
  '/code-file-tools/css-minifier': {
    name: 'CSS Minifier',
    category: 'File & Code Tools',
    categorySlug: 'code-file-tools',
    title: 'CSS Minifier - Free Online File & Code Tools Tool',
    description: 'Optimise stylesheets for production deployments. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'css minifier, css minifier online, free css minifier, code tool online, developer utility, minify tool, minify css online, free online tool, no signup, easytoolhub',
  },
  '/code-file-tools/javascript-minifier': {
    name: 'JavaScript Minifier',
    category: 'File & Code Tools',
    categorySlug: 'code-file-tools',
    title: 'JavaScript Minifier - Free Online File & Code Tools Tool',
    description: 'Compress scripts without breaking behaviour. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'javascript minifier, javascript minifier online, free javascript minifier, code tool online, developer utility, minify tool, js minifier, minify javascript online, free online tool, no signup, easytoolhub',
  },
  '/code-file-tools/html-entity-encoder': {
    name: 'HTML Entity Encoder',
    category: 'File & Code Tools',
    categorySlug: 'code-file-tools',
    title: 'HTML Entity Encoder - Free Online File & Code Tools Tool',
    description: 'Escape HTML entities for safer rendering. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'html entity encoder, html entity encoder online, free html entity encoder, html entity, entity encoder, code tool online, developer utility, minify tool, free online tool, no signup, easytoolhub',
  },
  '/code-file-tools/clipboard-viewer': {
    name: 'Clipboard Viewer',
    category: 'File & Code Tools',
    categorySlug: 'code-file-tools',
    title: 'Clipboard Viewer - Free Online File & Code Tools Tool',
    description: 'Inspect text, HTML, and images stored in your clipboard. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'clipboard viewer, clipboard viewer online, free clipboard viewer, code tool online, developer utility, minify tool, free online tool, no signup, easytoolhub',
  },
  '/code-file-tools/clipboard-history': {
    name: 'Clipboard History',
    category: 'File & Code Tools',
    categorySlug: 'code-file-tools',
    title: 'Clipboard History - Free Online File & Code Tools Tool',
    description: 'Keep multiple snippets ready for reuse. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'clipboard history, clipboard history online, free clipboard history, code tool online, developer utility, minify tool, free online tool, no signup, easytoolhub',
  },
  '/code-file-tools/file-metadata-viewer': {
    name: 'File Metadata Viewer',
    category: 'File & Code Tools',
    categorySlug: 'code-file-tools',
    title: 'File Metadata Viewer - Free Online File & Code Tools Tool',
    description: 'Understand file fingerprints right inside the browser. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'file metadata viewer, file metadata viewer online, free file metadata viewer, file metadata, metadata viewer, code tool online, developer utility, minify tool, free online tool, no signup, easytoolhub',
  },
  '/code-file-tools/markdown-to-pdf': {
    name: 'Markdown to PDF',
    category: 'File & Code Tools',
    categorySlug: 'code-file-tools',
    title: 'Markdown to PDF - Free Online File & Code Tools Tool',
    description: 'Turn technical documentation into polished PDFs. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'markdown to pdf, markdown to pdf online, free markdown to pdf, markdown pdf, code tool online, developer utility, minify tool, free online tool, no signup, easytoolhub',
  },
  '/code-file-tools/html-table-exporter': {
    name: 'HTML Table Exporter',
    category: 'File & Code Tools',
    categorySlug: 'code-file-tools',
    title: 'HTML Table Exporter - Free Online File & Code Tools Tool',
    description: 'Export tables to CSV, JSON, or Markdown. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'html table exporter, html table exporter online, free html table exporter, html table, table exporter, code tool online, developer utility, minify tool, free online tool, no signup, easytoolhub',
  },
  '/dev-design-tools/css-gradient-generator': {
    name: 'CSS Gradient Generator',
    category: 'Design & Web Dev Tools',
    categorySlug: 'dev-design-tools',
    title: 'CSS Gradient Generator - Free Online Tool',
    description: 'Craft brand-ready gradients with instant CSS output. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'css gradient generator, css gradient generator online, free css gradient generator, css gradient, gradient generator, web developer tool, css tool, api testing tool, gradient maker, free online tool, no signup, easytoolhub',
  },
  '/dev-design-tools/box-shadow-generator': {
    name: 'Box Shadow Generator',
    category: 'Design & Web Dev Tools',
    categorySlug: 'dev-design-tools',
    title: 'Box Shadow Generator - Free Online Tool',
    description: 'Preview elevation tokens with live CSS. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'box shadow generator, box shadow generator online, free box shadow generator, box shadow, shadow generator, web developer tool, css tool, api testing tool, css box shadow, free online tool, no signup, easytoolhub',
  },
  '/dev-design-tools/border-radius-preview': {
    name: 'Border Radius Preview',
    category: 'Design & Web Dev Tools',
    categorySlug: 'dev-design-tools',
    title: 'Border Radius Preview - Free Online Tool',
    description: 'Test corner radii across card layouts. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'border radius preview, border radius preview online, free border radius preview, border radius, radius preview, web developer tool, css tool, api testing tool, free online tool, no signup, easytoolhub',
  },
  '/dev-design-tools/pixel-to-rem': {
    name: 'Pixel to REM',
    category: 'Design & Web Dev Tools',
    categorySlug: 'dev-design-tools',
    title: 'Pixel to REM - Free Online Design & Web Dev Tools Tool',
    description: 'Translate measurements into scalable typography. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'pixel to rem, pixel to rem online, free pixel to rem, pixel rem, web developer tool, css tool, api testing tool, free online tool, no signup, easytoolhub',
  },
  '/dev-design-tools/responsive-breakpoint-tester': {
    name: 'Responsive Breakpoint Tester',
    category: 'Design & Web Dev Tools',
    categorySlug: 'dev-design-tools',
    title: 'Responsive Breakpoint Tester - Free Online Tool',
    description: 'Validate breakpoints alongside device data. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'responsive breakpoint tester, responsive breakpoint tester online, free responsive breakpoint tester, responsive breakpoint, breakpoint tester, web developer tool, css tool, api testing tool, free online tool, no signup, easytoolhub',
  },
  '/dev-design-tools/viewport-size-detector': {
    name: 'Viewport Size Detector',
    category: 'Design & Web Dev Tools',
    categorySlug: 'dev-design-tools',
    title: 'Viewport Size Detector - Free Online Tool',
    description: 'Inspect live viewport dimensions and media queries. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'viewport size detector, viewport size detector online, free viewport size detector, viewport size, size detector, web developer tool, css tool, api testing tool, free online tool, no signup, easytoolhub',
  },
  '/dev-design-tools/postman-lite': {
    name: 'Postman Lite',
    category: 'Design & Web Dev Tools',
    categorySlug: 'dev-design-tools',
    title: 'Postman Lite - Free Online Design & Web Dev Tools Tool',
    description: 'Send HTTP requests without leaving the browser. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'postman lite, postman lite online, free postman lite, web developer tool, css tool, api testing tool, free online tool, no signup, easytoolhub',
  },
  '/dev-design-tools/cors-test-tool': {
    name: 'CORS Test Tool',
    category: 'Design & Web Dev Tools',
    categorySlug: 'dev-design-tools',
    title: 'CORS Test Tool - Free Online Design & Web Dev Tools Tool',
    description: 'Test cross-origin request headers and CORS responses from any URL. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'cors test tool, cors test tool online, free cors test tool, cors test, web developer tool, css tool, api testing tool, cors tester, check cors headers, cross origin test, free online tool, no signup, easytoolhub',
  },
  '/dev-design-tools/http-header-decoder': {
    name: 'HTTP Header Decoder',
    category: 'Design & Web Dev Tools',
    categorySlug: 'dev-design-tools',
    title: 'HTTP Header Decoder - Free Online Tool',
    description: 'Inspect and validate request headers instantly. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'http header decoder, http header decoder online, free http header decoder, http header, header decoder, web developer tool, css tool, api testing tool, free online tool, no signup, easytoolhub',
  },
  '/dev-design-tools/websocket-client': {
    name: 'WebSocket Client',
    category: 'Design & Web Dev Tools',
    categorySlug: 'dev-design-tools',
    title: 'WebSocket Client - Free Online Design & Web Dev Tools Tool',
    description: 'Connect to WebSocket endpoints, send messages, and inspect responses live. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'websocket client, websocket client online, free websocket client, web developer tool, css tool, api testing tool, ws tester, websocket tester, socket.io client tool, free online tool, no signup, easytoolhub',
  },
  '/dev-design-tools/http-request-generator': {
    name: 'HTTP Request Generator',
    category: 'Design & Web Dev Tools',
    categorySlug: 'dev-design-tools',
    title: 'HTTP Request Generator - Free Online Tool',
    description: 'Test endpoints with configurable payloads. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'http request generator, http request generator online, free http request generator, http request, request generator, web developer tool, css tool, api testing tool, free online tool, no signup, easytoolhub',
  },
  '/dev-design-tools/mock-json-generator': {
    name: 'Mock JSON Generator',
    category: 'Design & Web Dev Tools',
    categorySlug: 'dev-design-tools',
    title: 'Mock JSON Generator - Free Online Tool',
    description: 'Seed prototypes with realistic dataset templates. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'mock json generator, mock json generator online, free mock json generator, mock json, json generator, web developer tool, css tool, api testing tool, free online tool, no signup, easytoolhub',
  },
  '/testing-tools/json-schema-validator': {
    name: 'JSON Schema Validator',
    category: 'Validation & Testing Tools',
    categorySlug: 'testing-tools',
    title: 'JSON Schema Validator - Free Online Tool',
    description: 'Check payloads against schema definitions. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'json schema validator, json schema validator online, free json schema validator, json schema, schema validator, validator online, testing utility, format checker, free online tool, no signup, easytoolhub',
  },
  '/testing-tools/password-rule-validator': {
    name: 'Password Rule Validator',
    category: 'Validation & Testing Tools',
    categorySlug: 'testing-tools',
    title: 'Password Rule Validator - Free Online Tool',
    description: 'Test policies against live credentials. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'password rule validator, password rule validator online, free password rule validator, password rule, rule validator, validator online, testing utility, format checker, free online tool, no signup, easytoolhub',
  },
  '/testing-tools/email-url-ip-checker': {
    name: 'Email, URL & IP Checker',
    category: 'Validation & Testing Tools',
    categorySlug: 'testing-tools',
    title: 'Email, URL & IP Checker - Free Online Tool',
    description: 'Verify addresses before persisting them. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'email, url & ip checker, email, url & ip checker online, free email, url & ip checker, email url ip checker, email url, url ip, ip checker, validator online, testing utility, format checker, free online tool, no signup, easytoolhub',
  },
  '/testing-tools/user-agent-parser': {
    name: 'User Agent Parser',
    category: 'Validation & Testing Tools',
    categorySlug: 'testing-tools',
    title: 'User Agent Parser - Free Online Tool',
    description: 'Parse headers into readable device profiles. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'user agent parser, user agent parser online, free user agent parser, user agent, agent parser, validator online, testing utility, format checker, free online tool, no signup, easytoolhub',
  },
  '/testing-tools/credit-card-validator': {
    name: 'Credit Card Validator',
    category: 'Validation & Testing Tools',
    categorySlug: 'testing-tools',
    title: 'Credit Card Validator - Free Online Tool',
    description: 'Confirm card numbers with Luhn and brand rules. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'credit card validator, credit card validator online, free credit card validator, credit card, card validator, validator online, testing utility, format checker, free online tool, no signup, easytoolhub',
  },
  '/testing-tools/jwt-decoder': {
    name: 'JWT Decoder',
    category: 'Validation & Testing Tools',
    categorySlug: 'testing-tools',
    title: 'JWT Decoder - Free Online Validation & Testing Tools Tool',
    description: 'Inspect JSON Web Tokens without sending them to a server. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'jwt decoder, jwt decoder online, free jwt decoder, validator online, testing utility, format checker, decode jwt token, jwt debugger, free online tool, no signup, easytoolhub',
  },
  '/security-tools/hash-generator': {
    name: 'Hash Generator',
    category: 'Security & Crypto Tools',
    categorySlug: 'security-tools',
    title: 'Hash Generator - Free Online Security & Crypto Tools Tool',
    description: 'Compute hashes across SHA, MD5, and more. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'hash generator, hash generator online, free hash generator, security tool, crypto utility, encryption tool, md5 hash, sha256 generator, sha512 hash, checksum calculator, free online tool, no signup, easytoolhub',
  },
  '/security-tools/uuid-generator': {
    name: 'UUID Generator',
    category: 'Security & Crypto Tools',
    categorySlug: 'security-tools',
    title: 'UUID Generator - Free Online Security & Crypto Tools Tool',
    description: 'Create unique identifiers for anything you ship. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'uuid generator, uuid generator online, free uuid generator, security tool, crypto utility, encryption tool, guid generator, random uuid v4, free online tool, no signup, easytoolhub',
  },
  '/security-tools/password-strength-checker': {
    name: 'Password Strength Checker',
    category: 'Security & Crypto Tools',
    categorySlug: 'security-tools',
    title: 'Password Strength Checker - Free Online Tool',
    description: 'Audit passwords against best practices. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'password strength checker, password strength checker online, free password strength checker, password strength, strength checker, security tool, crypto utility, encryption tool, password strength meter, check password strength, free online tool, no signup, easytoolhub',
  },
  '/security-tools/random-password-generator': {
    name: 'Random Password Generator',
    category: 'Security & Crypto Tools',
    categorySlug: 'security-tools',
    title: 'Random Password Generator - Free Online Tool',
    description: 'Generate strong credentials with policy-ready presets. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'random password generator, random password generator online, free random password generator, random password, password generator, security tool, crypto utility, encryption tool, strong password, random password maker, free online tool, no signup, easytoolhub',
  },
  '/security-tools/text-encrypt-decrypt': {
    name: 'Text Encrypt & Decrypt',
    category: 'Security & Crypto Tools',
    categorySlug: 'security-tools',
    title: 'Text Encrypt & Decrypt - Free Online Tool',
    description: 'Symmetric encryption for quick message sharing. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'text encrypt & decrypt, text encrypt & decrypt online, free text encrypt & decrypt, text encrypt decrypt, text encrypt, encrypt decrypt, security tool, crypto utility, encryption tool, free online tool, no signup, easytoolhub',
  },
  '/security-tools/secure-clipboard': {
    name: 'Secure Clipboard',
    category: 'Security & Crypto Tools',
    categorySlug: 'security-tools',
    title: 'Secure Clipboard - Free Online Security & Crypto Tools Tool',
    description: 'Keep snippets encrypted until you need them. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'secure clipboard, secure clipboard online, free secure clipboard, security tool, crypto utility, encryption tool, free online tool, no signup, easytoolhub',
  },
  '/security-tools/private-notes': {
    name: 'Private Notes',
    category: 'Security & Crypto Tools',
    categorySlug: 'security-tools',
    title: 'Private Notes - Free Online Security & Crypto Tools Tool',
    description: 'Draft notes that never leave your browser. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'private notes, private notes online, free private notes, security tool, crypto utility, encryption tool, free online tool, no signup, easytoolhub',
  },
  '/media-tools/voice-recorder': {
    name: 'Voice Recorder',
    category: 'Media & Audio Tools',
    categorySlug: 'media-tools',
    title: 'Voice Recorder - Free Online Media & Audio Tools Tool',
    description: 'Capture voice notes with local storage. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'voice recorder, voice recorder online, free voice recorder, audio tool online, video utility, media converter, free online tool, no signup, easytoolhub',
  },
  '/media-tools/audio-player': {
    name: 'Audio Player',
    category: 'Media & Audio Tools',
    categorySlug: 'media-tools',
    title: 'Audio Player - Free Online Media & Audio Tools Tool',
    description: 'Preview tracks with waveform and timeline controls. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'audio player, audio player online, free audio player, audio tool online, video utility, media converter, free online tool, no signup, easytoolhub',
  },
  '/media-tools/audio-trimmer': {
    name: 'Audio Trimmer',
    category: 'Media & Audio Tools',
    categorySlug: 'media-tools',
    title: 'Audio Trimmer - Free Online Media & Audio Tools Tool',
    description: 'Clip and export audio snippets right in your browser. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'audio trimmer, audio trimmer online, free audio trimmer, audio tool online, video utility, media converter, free online tool, no signup, easytoolhub',
  },
  '/media-tools/video-to-gif': {
    name: 'Video to GIF',
    category: 'Media & Audio Tools',
    categorySlug: 'media-tools',
    title: 'Video to GIF - Free Online Media & Audio Tools Tool',
    description: 'Create shareable loops without desktop software. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'video to gif, video to gif online, free video to gif, video gif, audio tool online, video utility, media converter, free online tool, no signup, easytoolhub',
  },
  '/media-tools/webcam-snapshot': {
    name: 'Webcam Snapshot',
    category: 'Media & Audio Tools',
    categorySlug: 'media-tools',
    title: 'Webcam Snapshot - Free Online Media & Audio Tools Tool',
    description: 'Take photos from your webcam in a click. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'webcam snapshot, webcam snapshot online, free webcam snapshot, audio tool online, video utility, media converter, free online tool, no signup, easytoolhub',
  },
  '/browser-utils/screen-resolution-info': {
    name: 'Screen Resolution Info',
    category: 'System / Browser Utilities',
    categorySlug: 'browser-utils',
    title: 'Screen Resolution Info - Free Online Tool',
    description: 'Surface dimensions, DPR, and orientation details. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'screen resolution info, screen resolution info online, free screen resolution info, screen resolution, resolution info, browser tool, system utility, web utility, free online tool, no signup, easytoolhub',
  },
  '/browser-utils/battery-status-viewer': {
    name: 'Battery Status Viewer',
    category: 'System / Browser Utilities',
    categorySlug: 'browser-utils',
    title: 'Battery Status Viewer - Free Online Tool',
    description: 'Monitor charging state and capacity in real time. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'battery status viewer, battery status viewer online, free battery status viewer, battery status, status viewer, browser tool, system utility, web utility, free online tool, no signup, easytoolhub',
  },
  '/browser-utils/device-orientation-logger': {
    name: 'Device Orientation Logger',
    category: 'System / Browser Utilities',
    categorySlug: 'browser-utils',
    title: 'Device Orientation Logger - Free Online Tool',
    description: 'Track motion data for hardware testing. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'device orientation logger, device orientation logger online, free device orientation logger, device orientation, orientation logger, browser tool, system utility, web utility, free online tool, no signup, easytoolhub',
  },
  '/browser-utils/storage-viewer': {
    name: 'Storage Viewer',
    category: 'System / Browser Utilities',
    categorySlug: 'browser-utils',
    title: 'Storage Viewer - Free Online System / Browser Utilities Tool',
    description: 'Explore localStorage and sessionStorage contents. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'storage viewer, storage viewer online, free storage viewer, browser tool, system utility, web utility, free online tool, no signup, easytoolhub',
  },
  '/browser-utils/cookie-editor': {
    name: 'Cookie Editor',
    category: 'System / Browser Utilities',
    categorySlug: 'browser-utils',
    title: 'Cookie Editor - Free Online System / Browser Utilities Tool',
    description: 'Edit, delete, and clone cookies securely. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'cookie editor, cookie editor online, free cookie editor, browser tool, system utility, web utility, free online tool, no signup, easytoolhub',
  },
  '/browser-utils/network-speed-test': {
    name: 'Network Speed Test',
    category: 'System / Browser Utilities',
    categorySlug: 'browser-utils',
    title: 'Network Speed Test - Free Online Tool',
    description: 'Measure download, upload, and latency benchmarks. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'network speed test, network speed test online, free network speed test, network speed, speed test, browser tool, system utility, web utility, internet speed test, bandwidth test, free online tool, no signup, easytoolhub',
  },
  '/fun-tools/qr-code-generator': {
    name: 'QR Code Generator',
    category: 'Fun & Productivity Tools',
    categorySlug: 'fun-tools',
    title: 'QR Code Generator - Free Online Tool',
    description: 'Create scannable QR codes with custom content in seconds. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'qr code generator, qr code generator online, free qr code generator, qr code, code generator, productivity tool, generator online, fun utility, create qr code, qr code maker, free online tool, no signup, easytoolhub',
  },
  '/fun-tools/barcode-generator': {
    name: 'Barcode Generator',
    category: 'Fun & Productivity Tools',
    categorySlug: 'fun-tools',
    title: 'Barcode Generator - Free Online Tool',
    description: 'Produce retail-ready barcodes on demand. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'barcode generator, barcode generator online, free barcode generator, productivity tool, generator online, fun utility, create barcode online, free online tool, no signup, easytoolhub',
  },
  '/fun-tools/stopwatch-timer': {
    name: 'Stopwatch & Timer',
    category: 'Fun & Productivity Tools',
    categorySlug: 'fun-tools',
    title: 'Stopwatch & Timer - Free Online Tool',
    description: 'Track precise durations and countdowns. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'stopwatch & timer, stopwatch & timer online, free stopwatch & timer, stopwatch timer, productivity tool, generator online, fun utility, free online tool, no signup, easytoolhub',
  },
  '/fun-tools/random-number-generator': {
    name: 'Random Number Generator',
    category: 'Fun & Productivity Tools',
    categorySlug: 'fun-tools',
    title: 'Random Number Generator - Free Online Tool',
    description: 'Draw fair numbers for raffles and tests. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'random number generator, random number generator online, free random number generator, random number, number generator, productivity tool, generator online, fun utility, free online tool, no signup, easytoolhub',
  },
  '/fun-tools/coin-toss-dice-roller': {
    name: 'Coin Toss & Dice Roller',
    category: 'Fun & Productivity Tools',
    categorySlug: 'fun-tools',
    title: 'Coin Toss & Dice Roller - Free Online Tool',
    description: 'Flip a coin or roll dice for quick random decisions and games. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'coin toss & dice roller, coin toss & dice roller online, free coin toss & dice roller, coin toss dice roller, coin toss, toss dice, dice roller, productivity tool, generator online, fun utility, coin toss online, flip a coin, random dice roller, free online tool, no signup, easytoolhub',
  },
  '/fun-tools/lorem-ipsum-generator': {
    name: 'Lorem Ipsum Generator',
    category: 'Fun & Productivity Tools',
    categorySlug: 'fun-tools',
    title: 'Lorem Ipsum Generator - Free Online Tool',
    description: 'Generate placeholder Lorem Ipsum paragraphs for mockups and wireframes. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'lorem ipsum generator, lorem ipsum generator online, free lorem ipsum generator, lorem ipsum, ipsum generator, productivity tool, generator online, fun utility, placeholder text generator, dummy text, lipsum generator, free online tool, no signup, easytoolhub',
  },
  '/fun-tools/timezone-converter': {
    name: 'Timezone Converter',
    category: 'Fun & Productivity Tools',
    categorySlug: 'fun-tools',
    title: 'Timezone Converter - Free Online Tool',
    description: 'Plan meetings globally without confusion. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'timezone converter, timezone converter online, free timezone converter, productivity tool, generator online, fun utility, free online tool, no signup, easytoolhub',
  },
  '/fun-tools/typing-speed-test': {
    name: 'Typing Speed Test',
    category: 'Fun & Productivity Tools',
    categorySlug: 'fun-tools',
    title: 'Typing Speed Test - Free Online Tool',
    description: 'Benchmark typing speed with live analytics. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'typing speed test, typing speed test online, free typing speed test, typing speed, speed test, productivity tool, generator online, fun utility, free online tool, no signup, easytoolhub',
  },
  '/fun-tools/pomodoro-timer': {
    name: 'Pomodoro Timer',
    category: 'Fun & Productivity Tools',
    categorySlug: 'fun-tools',
    title: 'Pomodoro Timer - Free Online Fun & Productivity Tools Tool',
    description: 'Stay on task with rhythm-based sprints. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'pomodoro timer, pomodoro timer online, free pomodoro timer, productivity tool, generator online, fun utility, free online tool, no signup, easytoolhub',
  },
  '/fun-tools/flashcard-quiz-generator': {
    name: 'Flashcard Quiz Generator',
    category: 'Fun & Productivity Tools',
    categorySlug: 'fun-tools',
    title: 'Flashcard Quiz Generator - Free Online Tool',
    description: 'Create study decks for any subject. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'flashcard quiz generator, flashcard quiz generator online, free flashcard quiz generator, flashcard quiz, quiz generator, productivity tool, generator online, fun utility, free online tool, no signup, easytoolhub',
  },
  '/fun-tools/motivational-quote-generator': {
    name: 'Motivational Quote Generator',
    category: 'Fun & Productivity Tools',
    categorySlug: 'fun-tools',
    title: 'Motivational Quote Generator - Free Online Tool',
    description: 'Get inspired with curated daily quotes. Free, fast, and private — runs in your browser on EasyToolHub.',
    keywords: 'motivational quote generator, motivational quote generator online, free motivational quote generator, motivational quote, quote generator, productivity tool, generator online, fun utility, free online tool, no signup, easytoolhub',
  },
};
