/**
 * Curated home-page ordering for general users first, specialist viewers second.
 * Update when analytics shows different trends or you launch a flagship tool.
 *
 * Paths use `category-slug/tool-slug` (no leading slash).
 * Tools not listed sort alphabetically after the listed ones.
 */

/** Everyday categories — ordered by what general users search for most. */
export const PRIMARY_HOME_CATEGORY_ORDER: readonly string[] = [
  'pdf-tools',
  'text-utilities',
  'image-color-tools',
  'data-converters',
  'security-tools',
  'file-viewers',
  'fun-tools',
  'math-date-utils',
  'code-file-tools',
  'dev-design-tools',
  'testing-tools',
  'browser-utils',
  'media-tools',
];

/**
 * Professional / niche viewers — ordered by broader appeal within specialist tools.
 * Collapsed on home until the user expands “Specialized viewers”.
 */
export const SPECIALIST_HOME_CATEGORY_ORDER: readonly string[] = [
  'diagram-viewers',
  'data-explorers',
  'network-viewers',
  'process-viewers',
  'gis-viewers',
  'science-viewers',
  'cad-viewers',
  'medical-viewers',
  'ml-viewers',
];

/** Full home order (primary first, then specialist). */
export const HOME_CATEGORY_ORDER: readonly string[] = [
  ...PRIMARY_HOME_CATEGORY_ORDER,
  ...SPECIALIST_HOME_CATEGORY_ORDER,
];

export const SPECIALIST_HOME_CATEGORY_SET = new Set<string>(SPECIALIST_HOME_CATEGORY_ORDER);

export function isSpecialistHomeCategory(categoryPath: string): boolean {
  return SPECIALIST_HOME_CATEGORY_SET.has(categoryPath);
}

/** Hero “Popular” strip — cross-category shortcuts. */
export const GLOBAL_POPULAR_TOOL_PATHS: readonly string[] = [
  'text-utilities/character-counter',
  'text-utilities/base64-encode-and-decode',
  'data-converters/json-formatter-beautifier-validator',
  'pdf-tools/merge-pdfs',
  'pdf-tools/pdf-viewer',
  'security-tools/hash-generator',
  'fun-tools/qr-code-generator',
  'text-utilities/url-encode-and-decode',
  'image-color-tools/image-compressor',
  'security-tools/random-password-generator',
  'text-utilities/regex-tester',
  'pdf-tools/compress-pdf',
];

/**
 * Per-category tool order — most-used first in every home card.
 * Lists every tool in the category so nothing falls back to random A–Z mid-list.
 */
export const POPULAR_TOOLS_BY_CATEGORY: Readonly<Record<string, readonly string[]>> = {
  'browser-utils': [
    'network-speed-test',
    'screen-resolution-info',
    'storage-viewer',
    'cookie-editor',
    'battery-status-viewer',
    'device-orientation-logger',
  ],
  'cad-viewers': [
    'dwg-viewer',
    'dxf-viewer',
    'step-viewer',
    'ifc-viewer',
    'sketchup-viewer',
    'pcb-layout-viewer',
    'gerber-file-viewer',
    'kicad-viewer',
    'solidworks-viewer',
    'revit-viewer',
    'dwf-viewer',
    'dgn-viewer',
    'iges-viewer',
    'fusion-360-viewer',
    'inventor-viewer',
    'catia-viewer',
    'creo-viewer',
    'rhino-3dm-viewer',
    'eagle-pcb-viewer',
    'altium-pcb-viewer',
    'parasolid-viewer',
    'plt-plot-viewer',
    'hpgl-viewer',
    'gdsii-layout-viewer',
    'navisworks-viewer',
    'bim-clash-viewer',
    'building-floor-plan-viewer',
    'mep-model-viewer',
    'structural-model-viewer',
  ],
  'code-file-tools': [
    'markdown-to-pdf',
    'html-minifier',
    'css-minifier',
    'javascript-minifier',
    'html-table-exporter',
    'clipboard-viewer',
    'html-entity-encoder',
    'clipboard-history',
    'file-metadata-viewer',
  ],
  'data-converters': [
    'json-formatter-beautifier-validator',
    'csv-to-json-json-to-csv',
    'yaml-to-json-json-to-yaml',
    'excel-to-json',
    'json-parser',
    'markdown-to-html',
    'html-table-to-json',
    'json-linter-viewer',
  ],
  'data-explorers': [
    'json-viewer',
    'csv-viewer',
    'sqlite-viewer',
    'yaml-viewer',
    'xml-viewer',
    'tsv-viewer',
    'duckdb-viewer',
    'parquet-viewer',
    'toml-viewer',
    'ini-viewer',
    'avro-viewer',
    'feather-viewer',
    'arrow-viewer',
    'orc-viewer',
    'delta-lake-viewer',
  ],
  'dev-design-tools': [
    'postman-lite',
    'css-gradient-generator',
    'cors-test-tool',
    'mock-json-generator',
    'websocket-client',
    'box-shadow-generator',
    'pixel-to-rem',
    'border-radius-preview',
    'http-request-generator',
    'http-header-decoder',
    'responsive-breakpoint-tester',
    'viewport-size-detector',
  ],
  'diagram-viewers': [
    'mermaid-diagram-viewer',
    'draw-io-viewer',
    'plantuml-viewer',
    'sql-schema-viewer',
    'er-diagram-viewer',
    'uml-viewer',
    'sequence-diagram-viewer',
    'class-diagram-viewer',
    'kubernetes-architecture-viewer',
    'terraform-graph-viewer',
    'mind-map-viewer',
    'graphviz-dot-viewer',
    'architecture-diagram-viewer',
    'c4-model-viewer',
    'dependency-graph-viewer',
    'dbml-viewer',
    'prisma-schema-viewer',
    'visio-viewer',
    'graphml-viewer',
    'gexf-viewer',
    'freemind-viewer',
    'freeplane-viewer',
    'concept-map-viewer',
    'state-machine-viewer',
    'decision-tree-viewer',
    'rdf-viewer',
    'owl-ontology-viewer',
    'knowledge-graph-viewer',
    'drools-rule-viewer',
  ],
  'file-viewers': [
    'pdf-viewer',
    'image-viewer',
    'word-viewer',
    'excel-viewer',
    'markdown-previewer',
    'text-file-viewer',
    'archive-viewer',
    'log-viewer',
    'ics-viewer',
    'svg-viewer',
    'epub-viewer',
    'powerpoint-viewer',
    'audio-player',
    'video-player',
    '3d-model-viewer',
    'heic-viewer',
    'tiff-viewer',
    'mobi-viewer',
    'latex-viewer',
    'opendocument-viewer',
    'rtf-viewer',
    'font-viewer',
    'psd-viewer',
    'ai-file-viewer',
    'raw-image-viewer',
    'xes-viewer',
    'subtitle-viewer',
    'midi-viewer',
    'musicxml-viewer',
    'wav-spectrum-viewer',
    'spectrogram-viewer',
    'apk-viewer',
    'ipa-viewer',
    'elf-binary-viewer',
    'pe-binary-viewer',
    'minecraft-world-viewer',
    'unity-asset-viewer',
    'game-save-viewer',
    'nft-metadata-viewer',
    'smart-contract-viewer',
    'invoice-data-viewer',
    'audit-log-viewer',
    'figma-export-viewer',
    'sketch-file-viewer',
    'indesign-viewer',
  ],
  'fun-tools': [
    'qr-code-generator',
    'lorem-ipsum-generator',
    'timezone-converter',
    'barcode-generator',
    'random-number-generator',
    'stopwatch-timer',
    'typing-speed-test',
    'pomodoro-timer',
    'coin-toss-dice-roller',
    'flashcard-quiz-generator',
    'motivational-quote-generator',
  ],
  'gis-viewers': [
    'geojson-viewer',
    'shapefile-viewer',
    'kml-viewer',
    'gpx-viewer',
    'geotiff-viewer',
    'kmz-viewer',
    'topojson-viewer',
    'dem-viewer',
    'geopackage-viewer',
    'mbtiles-viewer',
    'cog-viewer',
    'terrain-viewer',
    'contour-map-viewer',
    'gps-track-viewer',
    'satellite-image-viewer',
    'raster-map-viewer',
    'vector-tile-viewer',
    'lidar-map-viewer',
    'point-cloud-viewer',
    'drone-flight-path-viewer',
  ],
  'image-color-tools': [
    'image-compressor',
    'image-resizer',
    'image-to-base64',
    'color-picker',
    'hex-to-rgb',
    'image-to-text',
    'favicon-generator',
    'palette-generator',
    'gradient-generator',
    'drawing-pad',
  ],
  'math-date-utils': [
    'unit-converter',
    'percentage-calculator',
    'currency-converter',
    'age-calculator',
    'date-difference-calculator',
    'loan-emi-calculator',
    'bmi-calculator',
    'tip-calculator',
    'simple-compound-interest-calculator',
    'fraction-calculator',
    'number-to-words',
    'date-to-day-of-week',
    'zodiac-finder',
  ],
  'media-tools': [
    'voice-recorder',
    'audio-player',
    'video-to-gif',
    'audio-trimmer',
    'webcam-snapshot',
  ],
  'medical-viewers': [
    'dicom-viewer',
    'mri-viewer',
    'ct-scan-viewer',
    'x-ray-viewer',
    'nifti-viewer',
    'ultrasound-viewer',
    'mammography-viewer',
    'pet-scan-viewer',
    'fhir-resource-viewer',
    'hl7-message-viewer',
    'ecg-viewer',
    'eeg-viewer',
    'pathology-slide-viewer',
    'whole-slide-image-viewer',
    'medical-timeline-viewer',
    'nrrd-viewer',
    'minc-viewer',
    'cda-viewer',
  ],
  'ml-viewers': [
    'onnx-viewer',
    'tensorflow-graph-viewer',
    'pytorch-model-viewer',
    'keras-model-viewer',
    'mlflow-model-viewer',
    'neural-network-graph-viewer',
    'model-architecture-viewer',
    'tensor-visualization-viewer',
    'pickle-viewer',
  ],
  'network-viewers': [
    'har-viewer',
    'http-trace-viewer',
    'api-request-viewer',
    'pcap-viewer',
    'pcapng-viewer',
    'packet-analyzer',
    'network-traffic-viewer',
    'protocol-analyzer',
    'dns-log-viewer',
    'syslog-viewer',
    'firewall-log-viewer',
    'siem-log-viewer',
    'nmap-report-viewer',
    'nessus-report-viewer',
    'sarif-report-viewer',
    'malware-analysis-report-viewer',
    'threat-intelligence-viewer',
  ],
  'pdf-tools': [
    'merge-pdfs',
    'compress-pdf',
    'pdf-viewer',
    'split-pdfs',
    'image-to-pdf',
    'rotate-pages',
    'delete-pages',
    'extract-pages',
    'reorder-pages',
    'add-signature',
    'fill-pdf-forms',
    'password-protect-pdf',
    'add-watermark',
    'pdf-to-base64',
    'annotate-pdf',
    'highlight-text',
    'flatten-pdf-forms',
    'add-page-numbers',
    'text-to-pdf',
    'create-pdf-from-html',
    'html-to-pdf',
    'screenshot-to-pdf',
    'tables-charts-to-pdf',
    'tables-to-pdf',
    'charts-to-pdf',
    'resume-invoice-generator',
    'resume-generator',
    'invoice-generator',
    'pdf-metadata-editor',
    'barcode-to-pdf',
    'qr-code-to-pdf',
  ],
  'process-viewers': [
    'bpmn-viewer',
    'bpmn-analytics-viewer',
    'dmn-viewer',
    'process-mining-viewer',
    'event-log-viewer',
    'process-map-viewer',
    'workflow-diagram-viewer',
    'petri-net-viewer',
    'pnml-viewer',
    'decision-model-viewer',
    'epc-diagram-viewer',
    'bpel-viewer',
    'trace-explorer',
    'process-timeline-viewer',
    'business-process-simulator',
  ],
  'science-viewers': [
    'fasta-viewer',
    'fastq-viewer',
    'genbank-viewer',
    'molecular-structure-viewer',
    'protein-structure-viewer',
    'hdf5-viewer',
    'netcdf-viewer',
    'fits-viewer',
    'matlab-mat-viewer',
    'grib-viewer',
    'vcf-variant-viewer',
    'climate-data-viewer',
    'simulation-result-viewer',
    'las-well-log-viewer',
    'dlis-viewer',
    'seg-y-viewer',
    'geological-model-viewer',
    'borehole-viewer',
    'stratigraphy-viewer',
    'root-file-viewer',
  ],
  'security-tools': [
    'hash-generator',
    'random-password-generator',
    'uuid-generator',
    'password-strength-checker',
    'text-encrypt-decrypt',
    'secure-clipboard',
    'private-notes',
  ],
  'testing-tools': [
    'jwt-decoder',
    'json-schema-validator',
    'email-url-ip-checker',
    'user-agent-parser',
    'credit-card-validator',
    'password-rule-validator',
  ],
  'text-utilities': [
    'character-counter',
    'base64-encode-and-decode',
    'url-encode-and-decode',
    'text-case-convertor',
    'find-and-replace',
    'regex-tester',
    'slug-generator',
    'remove-duplicate-lines',
    'text-difference',
    'json-string-escape-unescape',
    'html-tag-stripper',
    'hex-encode-decode',
    'unicode-escape-unescape',
    'sort-lines',
    'trim-normalize-whitespace',
    'split-join-text',
    'line-number-tool',
    'word-wrap-unwrap',
    'extract-emails-urls',
    'pako-encode-and-decode',
    'readability-analyzer',
    'keyword-density',
    'text-similarity',
    'invisible-character-detector',
    'text-to-ascii',
    'text-reversal-and-palindrome-checker',
    'binary-text-converter',
    'rot13-cipher',
    'morse-code-converter',
    'code-merge',
  ],
};

export function normalizeToolPath(path: string): string {
  return path.replace(/^\/+/, '');
}

export function popularityRank(categoryPath: string, toolPath: string): number {
  const order = POPULAR_TOOLS_BY_CATEGORY[categoryPath];
  if (!order?.length) {
    return Number.MAX_SAFE_INTEGER;
  }
  const normalized = normalizeToolPath(toolPath);
  const slug = normalized.startsWith(`${categoryPath}/`)
    ? normalized.slice(categoryPath.length + 1)
    : normalized.split('/').pop() ?? normalized;
  const index = order.indexOf(slug);
  return index === -1 ? Number.MAX_SAFE_INTEGER : index;
}

export function categoryDisplayRank(categoryPath: string): number {
  const index = HOME_CATEGORY_ORDER.indexOf(categoryPath);
  return index === -1 ? Number.MAX_SAFE_INTEGER : index;
}
