import type { MincRelatedToolLink } from '../types/minc-viewer.types';

export const MINC_SUPPORTED_EXTENSIONS: ReadonlyArray<string> = ['.mnc', '.minc'];

export const MINC_ACCEPT_ATTR = '.mnc,.minc,application/octet-stream';

export const MINC_FORMATS_LABEL = '.mnc, .minc';

export const MINC_FORMATS_HINT =
  'MINC 1 / NetCDF classic volumes. MINC 2 (HDF5) is not decoded — convert first. Education/research only — not for diagnosis.';

export const MINC_MAX_FILE_BYTES = 120 * 1024 * 1024;

export const MINC_RELATED_TOOLS: ReadonlyArray<MincRelatedToolLink> = [
  { label: 'NIfTI Viewer', description: 'Neuroimaging volumes with ortho slices', path: '/medical-viewers/nifti-viewer' },
  { label: 'NRRD Viewer', description: 'Scientific volume grids with histogram', path: '/medical-viewers/nrrd-viewer' },
  { label: 'MRI Viewer', description: 'MRI series navigate and window/level', path: '/medical-viewers/mri-viewer' }
];

export const MINC_SAMPLE_BASE64 = 'Q0RGAQAAAAAAAAAKAAAADHhzcGFjZQAAAAAACAAAAAoAAAAMeXNwYWNlAAAAAAAIAAAACgAAAAx6c3BhY2UAAAAAAAQAAAALAAAAJGltYWdlAAAAAAAAAwAAAAAAAAABAAAAAgAAAAUAAAQAAAAAcAAAAAA/gAAAQAAAAEBAAABAgAAAQKAAAEDAAABA4AAAQSAAAEEwAABBQAAAQVAAAEFgAABBcAAAQYAAAEGIAABBoAAAQagAAEGwAABBuAAAQcAAAEHIAABB0AAAQdgAAEHwAABB+AAAQgAAAEIEAABCCAAAQgwAAEIQAABCFAAAQiAAAEIkAABCKAAAQiwAAEIwAABCNAAAQjgAAEI8AABCSAAAQkwAAEJQAABCVAAAQlgAAEJcAABCYAAAQmQAAEJwAABCdAAAQngAAEJ8AABCgAAAQoIAAEKEAABChgAAQowAAEKOAABCkAAAQpIAAEKUAABClgAAQpgAAEKaAABCyAAAQsoAAELMAABCzgAAQtAAAELSAABC1AAAQtYAAELcAABC3gAAQuAAAELiAABC5AAAQuYAAELoAABC6gAAQvAAAELyAABC9AAAQvYAAEL4AABC+gAAQvwAAEL+AABDAgAAQwMAAEMEAABDBQAAQwYAAEMHAABDCAAAQwkAAEMMAABDDQAAQw4AAEMPAABDEAAAQxEAAEMSAABDEwAAQxYAAEMXAABDGAAAQxkAAEMaAABDGwAAQxwAAEMdAABDIAAAQyEAAEMiAABDIwAAQyQAAEMlAABDJgAAQycAAEMqAABDKwAAQywAAEMtAABDLgAAQy8AAEMwAABDMQAAQ0gAAENJAABDSgAAQ0sAAENMAABDTQAAQ04AAENPAABDUgAAQ1MAAENUAABDVQAAQ1YAAENXAABDWAAAQ1kAAENcAABDXQAAQ14AAENfAABDYAAAQ2EAAENiAABDYwAAQ2YAAENnAABDaAAAQ2kAAENqAABDawAAQ2wAAENtAABDcAAAQ3EAAENyAABDcwAAQ3QAAEN1AABDdgAAQ3cAAEN6AABDewAAQ3wAAEN9AABDfgAAQ38AAEOAAABDgIAAQ4IAAEOCgABDgwAAQ4OAAEOEAABDhIAAQ4UAAEOFgABDhwAAQ4eAAEOIAABDiIAAQ4kAAEOJgABDigAAQ4qAAEOWAABDloAAQ5cAAEOXgABDmAAAQ5iAAEOZAABDmYAAQ5sAAEObgABDnAAAQ5yAAEOdAABDnYAAQ54AAEOegABDoAAAQ6CAAEOhAABDoYAAQ6IAAEOigABDowAAQ6OAAEOlAABDpYAAQ6YAAEOmgABDpwAAQ6eAAEOoAABDqIAAQ6oAAEOqgABDqwAAQ6uAAEOsAABDrIAAQ60AAEOtgABDrwAAQ6+AAEOwAABDsIAAQ7EAAEOxgABDsgAAQ7KAAEO0AABDtIAAQ7UAAEO1gABDtgAAQ7aAAEO3AABDt4AAQ7kAAEO5gABDugAAQ7qAAEO7AABDu4AAQ7wAAEO8gAA=';
