import type { MriRelatedToolLink, MriWindowPreset } from '../types/mri-viewer.types';

export const MRI_SUPPORTED_EXTENSIONS: ReadonlyArray<string> = ['.dcm', '.dicom', '.ima'];

export const MRI_ACCEPT_ATTR = '.dcm,.dicom,.ima,application/dicom';

export const MRI_FORMATS_LABEL = '.dcm, .dicom, .ima';

export const MRI_FORMATS_HINT =
  'Prefer Modality MR DICOM series. Soft warning for other modalities — still loads. Education/research only — not for diagnosis.';

export const MRI_MAX_FILE_BYTES = 80 * 1024 * 1024;

export const MRI_PREFERRED_MODALITY = 'MR';

export const MRI_RELATED_TOOLS: ReadonlyArray<MriRelatedToolLink> = [
  {
    label: 'DICOM Viewer',
    description: 'Generic DICOM window/level preview',
    path: '/medical-viewers/dicom-viewer'
  },
  {
    label: 'NIfTI Viewer',
    description: 'Neuroimaging volumes with ortho slices',
    path: '/medical-viewers/nifti-viewer'
  },
  {
    label: 'CT Scan Viewer',
    description: 'CT slices, HU probe, and measure',
    path: '/medical-viewers/ct-scan-viewer'
  },
  {
    label: 'X-Ray Viewer',
    description: 'Radiograph zoom and window/level',
    path: '/medical-viewers/x-ray-viewer'
  }
];

export const MRI_WINDOW_PRESETS: ReadonlyArray<MriWindowPreset> = [
  { id: 'brain-t1', label: 'Brain T1-ish', center: 600, width: 1200 },
  { id: 'brain-t2', label: 'Brain T2-ish', center: 900, width: 1800 },
  { id: 'spine-soft', label: 'Spine soft', center: 400, width: 1000 },
  { id: 'soft', label: 'Soft tissue', center: 300, width: 800 }
];

/**
 * Tiny 32×32 MONOCHROME2 MR DICOM (Explicit VR LE) for offline smoke tests.
 * Decoded bytes match /tmp/sample-mr.dcm.b64.
 */
export const MRI_SAMPLE_BASE64 =
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABESUNNAgAAAFVMBACiAAAAAgABAFVJFAAxLjIuODQwLjEwMDA4LjEuMi4xIAIAAgBVSRoAMS4yLjg0MC4xMDAwOC41LjEuNC4xLjEuNyACAAMAVUkUADEuMi44NDAuMTEzNjE5LjIuMS4xAgAQAFVJFAAxLjIuODQwLjEwMDA4LjEuMi4xIAIAEgBVSRAAMS4yLjg0MC4xMTM2MTkuMQIAEwBTSAwARWFzeVRvb2xIdWIgCABgAENTAgBNUggAFgBVSRoAMS4yLjg0MC4xMDAwOC41LjEuNC4xLjEuNyAIABgAVUkUADEuMi44NDAuMTEzNjE5LjIuMS4yCABwAExPDABFYXN5VG9vbEh1YiAQABAAUE4OAFNhbXBsZV5QYXRpZW50EAAgAExPCgBTQU1QTEUwMDEgKAACAFVTAgABACgABABDUwwATU9OT0NIUk9NRTIgKAAQAFVTAgAgACgAEQBVUwIAIAAoAAABVVMCABAAKAABAVVTAgAMACgAAgFVUwIACwAoAAMBVVMCAAAAKABQEERTBAAxMDAwKABREERTBAAyMDAwKABSEERTAgAwICgAUxBEUwIAMSDgfxAAT1cAAAAIAADIAMgAyADIAMgAyADIAMgAyADIAMkAyQDJAMkAyQDJAMkAyQDJAMkAyQDJAMkAyADIAMgAyADIAMgAyADIAMgAyADIAMgAyADIAMgAyADIAMkAyQDJAMoAygDKAMsAywDLAMsAywDKAMoAygDJAMkAyQDIAMgAyADIAMgAyADIAMgAyADIAMgAyADIAMgAyQDJAMoAygDLAMwAzQDNAM4AzgDOAM0AzQDMAMsAygDKAMkAyQDIAMgAyADIAMgAyADIAMgAyADIAMgAyQDJAMoAygDLAM0AzgDQANEA0wDTANQA0wDTANEA0ADOAM0AywDKAMoAyQDJAMgAyADIAMgAyADIAMgAyADJAMkAygDLAMwAzgDRANQA1wDZANwA3QDeAN0A3ADZANcA1ADRAM4AzADLAMoAyQDJAMgAyADIAMgAyADIAMkAyQDKAMsAzQDQANMA2ADdAOIA5wDrAO4A7wDuAOsA5wDiAN0A2ADTANAAzQDLAMoAyQDJAMgAyADIAMgAyADJAMoAywDNANEA1QDbAOMA6wD0APwAAwEIAQoBCAEDAfwA9ADrAOMA2wDVANEAzQDLAMoAyQDIAMgAyADIAMkAygDLAM0A0QDWAN0A5wDzAAEBDwEcASgBLwEyAS8BKAEcAQ8BAQHzAOcA3QDWANEAzQDLAMoAyQDIAMgAyQDJAMoAzADQANUA3QDpAPcACgEeATQBSQFaAWYBagFmAVoBSQE0AR4BCgH3AOkA3QDVANAAzADKAMkAyQDIAMkAygDLAM4A0wDbAOcA9wANASgBRgFmAYQBnQGtAbMBrQGdAYQBZgFGASgBDQH3AOcA2wDTAM4AywDKAMkAyQDJAMoAzQDRANgA4wDzAAoBKAFMAXYBogHMAe4BBQINAgUC7gHMAaIBdgFMASgBCgHzAOMA2ADRAM0AygDJAMkAygDLAM4A1ADdAOsAAQEeAUYBdgGtAecBHgJLAmoCdAJqAksCHgLnAa0BdgFGAR4BAQHrAN0A1ADOAMsAygDJAMoAzADQANcA4gD0AA8BNAFmAaIB5wEvAnQCrQLTAuAC0wKtAnQCLwLnAaIBZgE0AQ8B9ADiANcA0ADMAMoAyQDKAM0A0QDZAOcA/AAcAUkBhAHMAR4CdALGAgoDNwNHAzcDCgPGAnQCHgLMAYQBSQEcAfwA5wDZANEAzQDKAMkAywDNANMA3ADrAAMBKAFaAZ0B7gFLAq0CCgNXA4oDnAOKA1cDCgOtAksC7gGdAVoBKAEDAesA3ADTAM0AywDJAMsAzgDTAN0A7gAIAS8BZgGtAQUCagLTAjcDigPBA9QDwQOKAzcD0wJqAgUCrQFmAS8BCAHuAN0A0wDOAMsAyQDLAM4A1ADeAO8ACgEyAWoBswENAnQC4AJHA5wD1APoA9QDnANHA+ACdAINArMBagEyAQoB7wDeANQAzgDLAMkAywDOANMA3QDuAAgBLwFmAa0BBQJqAtMCNwOKA8ED1APBA4oDNwPTAmoCBQKtAWYBLwEIAe4A3QDTAM4AywDJAMsAzQDTANwA6wADASgBWgGdAe4BSwKtAgoDVwOKA5wDigNXAwoDrQJLAu4BnQFaASgBAwHrANwA0wDNAMsAyQDKAM0A0QDZAOcA/AAcAUkBhAHMAR4CdALGAgoDNwNHAzcDCgPGAnQCHgLMAYQBSQEcAfwA5wDZANEAzQDKAMkAygDMANAA1wDiAPQADwE0AWYBogHnAS8CdAKtAtMC4ALTAq0CdAIvAucBogFmATQBDwH0AOIA1wDQAMwAygDJAMoAywDOANQA3QDrAAEBHgFGAXYBrQHnAR4CSwJqAnQCagJLAh4C5wGtAXYBRgEeAQEB6wDdANQAzgDLAMoAyQDJAMoAzQDRANgA4wDzAAoBKAFMAXYBogHMAe4BBQINAgUC7gHMAaIBdgFMASgBCgHzAOMA2ADRAM0AygDJAMgAyQDKAMsAzgDTANsA5wD3AA0BKAFGAWYBhAGdAa0BswGtAZ0BhAFmAUYBKAENAfcA5wDbANMAzgDLAMoAyQDIAMkAyQDKAMwA0ADVAN0A6QD3AAoBHgE0AUkBWgFmAWoBZgFaAUkBNAEeAQoB9wDpAN0A1QDQAMwAygDJAMkAyADIAMkAygDLAM0A0QDWAN0A5wDzAAEBDwEcASgBLwEyAS8BKAEcAQ8BAQHzAOcA3QDWANEAzQDLAMoAyQDIAMgAyADIAMkAygDLAM0A0QDVANsA4wDrAPQA/AADAQgBCgEIAQMB/AD0AOsA4wDbANUA0QDNAMsAygDJAMgAyADIAMgAyADJAMkAygDLAM0A0ADTANgA3QDiAOcA6wDuAO8A7gDrAOcA4gDdANgA0wDQAM0AywDKAMkAyQDIAMgAyADIAMgAyADJAMkAygDLAMwAzgDRANQA1wDZANwA3QDeAN0A3ADZANcA1ADRAM4AzADLAMoAyQDJAMgAyADIAMgAyADIAMgAyADJAMkAygDKAMsAzQDOANAA0QDTANMA1ADTANMA0QDQAM4AzQDLAMoAygDJAMkAyADIAMgAyADIAMgAyADIAMgAyADIAMkAyQDKAMoAywDMAM0AzQDOAM4AzgDNAM0AzADLAMoAygDJAMkAyADIAMgAyADIAMgAyADIAMgAyADIAMgAyADIAMkAyQDJAMoAygDKAMsAywDLAMsAywDKAMoAygDJAMkAyQDIAMgAyADIAMgAyADIAA==';
