import type { XRayRelatedToolLink, XRayWindowPreset } from '../types/x-ray-viewer.types';

export const XRAY_SUPPORTED_EXTENSIONS: ReadonlyArray<string> = ['.dcm', '.dicom', '.ima'];

export const XRAY_ACCEPT_ATTR = '.dcm,.dicom,.ima,application/dicom';

export const XRAY_FORMATS_LABEL = '.dcm, .dicom, .ima';

export const XRAY_FORMATS_HINT =
  'Prefer Modality CR/DX/XR/RF radiograph DICOM. Soft warning for other modalities — still loads. Education/research only — not for diagnosis.';

export const XRAY_MAX_FILE_BYTES = 80 * 1024 * 1024;

export const XRAY_PREFERRED_MODALITIES: ReadonlyArray<string> = ['CR', 'DX', 'XR', 'RF'];

export const XRAY_RELATED_TOOLS: ReadonlyArray<XRayRelatedToolLink> = [
  {
    label: 'DICOM Viewer',
    description: 'Generic DICOM window/level preview',
    path: '/medical-viewers/dicom-viewer'
  },
  {
    label: 'CT Scan Viewer',
    description: 'CT slices, HU probe, and measure',
    path: '/medical-viewers/ct-scan-viewer'
  },
  {
    label: 'Ultrasound Viewer',
    description: 'US cine loops and metadata',
    path: '/medical-viewers/ultrasound-viewer'
  },
  {
    label: 'Mammography Viewer',
    description: 'MG hanging layout and zoom',
    path: '/medical-viewers/mammography-viewer'
  }
];

export const XRAY_WINDOW_PRESETS: ReadonlyArray<XRayWindowPreset> = [
  { id: 'chest', label: 'Chest', center: 400, width: 1500 },
  { id: 'bone', label: 'Bone', center: 500, width: 2000 },
  { id: 'abdomen', label: 'Abdomen', center: 50, width: 350 },
  { id: 'soft', label: 'Soft tissue', center: 350, width: 800 }
];

/** Tiny 32×32 MONOCHROME2 DX DICOM (Explicit VR LE) for offline smoke tests. */
export const XRAY_SAMPLE_BASE64 =
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABESUNNAgAAAFVMBACiAAAAAgABAFVJFAAxLjIuODQwLjEwMDA4LjEuMi4xIAIAAgBVSRoAMS4yLjg0MC4xMDAwOC41LjEuNC4xLjEuNyACAAMAVUkUADEuMi44NDAuMTEzNjE5LjIuMS4xAgAQAFVJFAAxLjIuODQwLjEwMDA4LjEuMi4xIAIAEgBVSRAAMS4yLjg0MC4xMTM2MTkuMQIAEwBTSAwARWFzeVRvb2xIdWIgCABgAENTAgBEWAgAFgBVSRoAMS4yLjg0MC4xMDAwOC41LjEuNC4xLjEuNyAIABgAVUkUADEuMi44NDAuMTEzNjE5LjIuMS4yCABwAExPDABFYXN5VG9vbEh1YiAQABAAUE4OAFNhbXBsZV5QYXRpZW50EAAgAExPCgBTQU1QTEUwMDEgKAACAFVTAgABACgABABDUwwATU9OT0NIUk9NRTIgKAAQAFVTAgAgACgAEQBVUwIAIAAoAAABVVMCABAAKAABAVVTAgAMACgAAgFVUwIACwAoAAMBVVMCAAAAKABQEERTBAAxMDAwKABREERTBAAyMDAwKABSEERTAgAwICgAUxBEUwIAMSDgfxAAT1cAAAAIAADIAMgAyADIAMgAyADIAMgAyADIAMkAyQDJAMkAyQDJAMkAyQDJAMkAyQDJAMkAyADIAMgAyADIAMgAyADIAMgAyADIAMgAyADIAMgAyADIAMkAyQDJAMoAygDKAMsAywDLAMsAywDKAMoAygDJAMkAyQDIAMgAyADIAMgAyADIAMgAyADIAMgAyADIAMgAyQDJAMoAygDLAMwAzQDNAM4AzgDOAM0AzQDMAMsAygDKAMkAyQDIAMgAyADIAMgAyADIAMgAyADIAMgAyQDJAMoAygDLAM0AzgDQANEA0wDTANQA0wDTANEA0ADOAM0AywDKAMoAyQDJAMgAyADIAMgAyADIAMgAyADJAMkAygDLAMwAzgDRANQA1wDZANwA3QDeAN0A3ADZANcA1ADRAM4AzADLAMoAyQDJAMgAyADIAMgAyADIAMkAyQDKAMsAzQDQANMA2ADdAOIA5wDrAO4A7wDuAOsA5wDiAN0A2ADTANAAzQDLAMoAyQDJAMgAyADIAMgAyADJAMoAywDNANEA1QDbAOMA6wD0APwAAwEIAQoBCAEDAfwA9ADrAOMA2wDVANEAzQDLAMoAyQDIAMgAyADIAMkAygDLAM0A0QDWAN0A5wDzAAEBDwEcASgBLwEyAS8BKAEcAQ8BAQHzAOcA3QDWANEAzQDLAMoAyQDIAMgAyQDJAMoAzADQANUA3QDpAPcACgEeATQBSQFaAWYBagFmAVoBSQE0AR4BCgH3AOkA3QDVANAAzADKAMkAyQDIAMkAygDLAM4A0wDbAOcA9wANASgBRgFmAYQBnQGtAbMBrQGdAYQBZgFGASgBDQH3AOcA2wDTAM4AywDKAMkAyQDJAMoAzQDRANgA4wDzAAoBKAFMAXYBogHMAe4BBQINAgUC7gHMAaIBdgFMASgBCgHzAOMA2ADRAM0AygDJAMkAygDLAM4A1ADdAOsAAQEeAUYBdgGtAecBHgJLAmoCdAJqAksCHgLnAa0BdgFGAR4BAQHrAN0A1ADOAMsAygDJAMoAzADQANcA4gD0AA8BNAFmAaIB5wEvAnQCrQLTAuAC0wKtAnQCLwLnAaIBZgE0AQ8B9ADiANcA0ADMAMoAyQDKAM0A0QDZAOcA/AAcAUkBhAHMAR4CdALGAgoDNwNHAzcDCgPGAnQCHgLMAYQBSQEcAfwA5wDZANEAzQDKAMkAywDNANMA3ADrAAMBKAFaAZ0B7gFLAq0CCgNXA4oDnAOKA1cDCgOtAksC7gGdAVoBKAEDAesA3ADTAM0AywDJAMsAzgDTAN0A7gAIAS8BZgGtAQUCagLTAjcDigPBA9QDwQOKAzcD0wJqAgUCrQFmAS8BCAHuAN0A0wDOAMsAyQDLAM4A1ADeAO8ACgEyAWoBswENAnQC4AJHA5wD1APoA9QDnANHA+ACdAINArMBagEyAQoB7wDeANQAzgDLAMkAywDOANMA3QDuAAgBLwFmAa0BBQJqAtMCNwOKA8ED1APBA4oDNwPTAmoCBQKtAWYBLwEIAe4A3QDTAM4AywDJAMsAzQDTANwA6wADASgBWgGdAe4BSwKtAgoDVwOKA5wDigNXAwoDrQJLAu4BnQFaASgBAwHrANwA0wDNAMsAyQDKAM0A0QDZAOcA/AAcAUkBhAHMAR4CdALGAgoDNwNHAzcDCgPGAnQCHgLMAYQBSQEcAfwA5wDZANEAzQDKAMkAygDMANAA1wDiAPQADwE0AWYBogHnAS8CdAKtAtMC4ALTAq0CdAIvAucBogFmATQBDwH0AOIA1wDQAMwAygDJAMoAywDOANQA3QDrAAEBHgFGAXYBrQHnAR4CSwJqAnQCagJLAh4C5wGtAXYBRgEeAQEB6wDdANQAzgDLAMoAyQDJAMoAzQDRANgA4wDzAAoBKAFMAXYBogHMAe4BBQINAgUC7gHMAaIBdgFMASgBCgHzAOMA2ADRAM0AygDJAMgAyQDKAMsAzgDTANsA5wD3AA0BKAFGAWYBhAGdAa0BswGtAZ0BhAFmAUYBKAENAfcA5wDbANMAzgDLAMoAyQDIAMkAyQDKAMwA0ADVAN0A6QD3AAoBHgE0AUkBWgFmAWoBZgFaAUkBNAEeAQoB9wDpAN0A1QDQAMwAygDJAMkAyADIAMkAygDLAM0A0QDWAN0A5wDzAAEBDwEcASgBLwEyAS8BKAEcAQ8BAQHzAOcA3QDWANEAzQDLAMoAyQDIAMgAyADIAMkAygDLAM0A0QDVANsA4wDrAPQA/AADAQgBCgEIAQMB/AD0AOsA4wDbANUA0QDNAMsAygDJAMgAyADIAMgAyADJAMkAygDLAM0A0ADTANgA3QDiAOcA6wDuAO8A7gDrAOcA4gDdANgA0wDQAM0AywDKAMkAyQDIAMgAyADIAMgAyADJAMkAygDLAMwAzgDRANQA1wDZANwA3QDeAN0A3ADZANcA1ADRAM4AzADLAMoAyQDJAMgAyADIAMgAyADIAMgAyADJAMkAygDKAMsAzQDOANAA0QDTANMA1ADTANMA0QDQAM4AzQDLAMoAygDJAMkAyADIAMgAyADIAMgAyADIAMgAyADIAMkAyQDKAMoAywDMAM0AzQDOAM4AzgDNAM0AzADLAMoAygDJAMkAyADIAMgAyADIAMgAyADIAMgAyADIAMgAyADIAMkAyQDJAMoAygDKAMsAywDLAMsAywDKAMoAygDJAMkAyQDIAMgAyADIAMgAyADIAA==';
